#+Title:     SLAT: Example 2
#+AUTHOR:    Michael Gauland
#+EMAIL:     michael.gauland@canterbury.ac.nz
#+DATE:      {{{time(%Y-%m-%d %H:%M)}}}
#+DESCRIPTION: 
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:6 num:t toc:4 \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:dvipng LaTeX:dvipng skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   timestamp:t email:t
#+OPTIONS:   ':t
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{unicode-math}
#+LaTex_header: \usepackage{epstopdf}
#+LATEX_HEADER: \usepackage{register}
#+LATEX_HEADER: \usepackage{bytefield}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabulary}
#+LATEX_HEADER: \usepackage[section]{placeins}
#+LATEX_HEADER: \usepackage[htt]{hyphenat}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \lstset{keywordstyle=\color{blue}\bfseries}
#+LATEX_HEADER: \newfontfamily\listingsfont[Scale=.7]{DejaVu Sans Mono}
#+LATEX_HEADER: \lstset{basicstyle=\listingsfont}
#+LATEX_HEADER: \lstset{showspaces=false}
#+LATEX_HEADER: \lstset{columns=fixed}
#+LATEX_HEADER: \lstset{extendedchars=true}
#+LATEX_HEADER: \lstset{frame=shadowbox}
#+LATEX_HEADER: \lstset{basicstyle=\ttfamily}
#+LATEX_HEADER: \definecolor{mygray}{gray}{0.8}
#+LATEX_HEADER: \lstset{rulesepcolor=\color{mygray}}
#+LATEX_HEADER: \lstdefinelanguage{dash}{rulecolor=\color{green},rulesepcolor=\color{mygray},frameround=ffff,backgroundcolor=\color{white}}
#+LATEX_HEADER: \lstdefinelanguage{fundamental}{basicstyle=\ttfamily\scriptsize,rulesepcolor=\color{cyan},frameround=tttt,backgroundcolor=\color{white},breaklines=true}
#+LATEX_HEADER: \usepackage{pst-circ}
#+LATEX_HEADER: \usepackage[hang,small,bf]{caption}
#+LATEX_HEADER: \setlength{\captionmargin}{20pt}
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+STARTUP: overview
#+STARTUP: align
#+STARTUP: noinlineimages
#+PROPERTY: header-args:R  :session *R-2*
#+PROPERTY: header-args    :exports both

\clearpage
* Initialisation

  The code in this section reads in the input data, as well as the results
  produces by the old ("paleo") and new ("neo") versions of SLAT.

  #+BEGIN_SRC R  :results output 
    library(xtable)

    num.edps <- 21
    num.cgs <- 115


    ##Set up variables to make it easier to get to the files:
    paleo.dir = paste("~/SLATv1.15_Public/",
        "example2_10storeybuilding/", sep="")
    results.dir = paste(paleo.dir, "results/", sep="")

    ## Read in the IM data:
    paleo.im <- read.csv(
        paste(results.dir, "im_rate", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.im) = c("IM", "lambda")

    neo.im <- read.csv("results/im_rate", 
                       header=TRUE, sep="")

    ## Read the EDP-IM data
    paleo.edp.im = list()
    neo.edp.im = list()

    for (i in seq(num.edps)) {
        ## Read data from old SLAT:
        paleo.edp.im[[i]] <- read.csv(
            sprintf("%sim_edp_%d.txt", results.dir, i),
            skip=3, header=FALSE, sep="")
        names(paleo.edp.im[[i]]) = c("IM", "mean.x", "sd.lnx")

        neo.edp.im[[i]] <- read.csv(
            sprintf("results/im_edp_%d.txt", i),
            header=TRUE, sep="")
        names(neo.edp.im[[i]]) = c("IM", "mean.x", "sd.lnx")

        if (length(paleo.edp.im[[i]]$IM) !=
            length(neo.edp.im[[i]]$IM) ||
            (max(abs((paleo.edp.im[[i]]$IM -
              	    neo.edp.im[[i]]$IM)/
                              paleo.edp.im[[i]]$IM)) > 1))
            {
                print(sprintf("IM mismatch in EDP-IM #%d", i))
                break
            }
    }

    ## Read the EDP-Rate data
    paleo.edp.rate = list()
    neo.edp.rate = list()

    for (i in seq(num.edps)) {
        ## Read data from old SLAT:
        paleo.edp.rate[[i]] <- read.csv(
            sprintf("%sedp_%d_rate.txt", results.dir, i),
            skip=3, header=FALSE, sep="")
        names(paleo.edp.rate[[i]]) = c("EDP", "lambda")

        neo.edp.rate[[i]] <- read.csv(
            sprintf("results/edp_%d_rate.txt", i),
            header=TRUE, sep="")
        names(neo.edp.rate[[i]]) = c("EDP", "lambda")

        if (length(paleo.edp.rate[[i]]$EDP) !=  
            length(neo.edp.rate[[i]]$EDP) ||
            (max(abs((paleo.edp.rate[[i]]$EDP -
              	    neo.edp.rate[[i]]$EDP)/
                              paleo.edp.rate[[i]]$EDP)) > 1)) 
            {
                print(sprintf("EDP mismatch in EDP-RATE #%d",
                              i))
                break
            }
    }

    ## Read the colapse-im data:
    paleo.collapse.im <- read.csv(
        paste(results.dir, "collapse.txt", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.collapse.im) = c("IM", "pCollapse")

    neo.collapse.im <- read.csv("results/collapse.txt", 
                                header=TRUE, sep="")
    names(neo.collapse.im) = c("IM", "pDemolition", "pCollapse")

    if (length(paleo.collapse.im$IM) !=
        length(neo.collapse.im$IM) ||
        (max(abs((paleo.collapse.im$IM -
                      neo.collapse.im$IM)/
            	      paleo.collapse.im$IM)) > 1))
        {
            print("IM mismatch in COLLAPSE-RATE")
            break
        }

    ## Read the Component Group loss data
    paleo.loss.im <- list()
    paleo.loss.edp <- list()
    neo.loss.im <- list()
    neo.loss.edp <- list()

    for (i in seq(num.cgs)) {
        paleo.loss.im[[i]] <- read.csv(
            sprintf("%sloss_%d_im.txt", results.dir, i),
            skip=3, header=FALSE, sep="")
        names(paleo.loss.im[[i]]) = c("IM","mean.x","sd.lnx")

        neo.loss.im[[i]] <- read.csv(
            sprintf("results/loss_%d_im.txt", i),
            header=TRUE, sep="")
        names(neo.loss.im[[i]]) = c("IM","mean.x","sd.lnx")

        if (length(paleo.loss.im[[i]]$IM) != 
            length(neo.loss.im[[i]]$IM) ||
            (max(abs((paleo.loss.im[[i]]$IM - 
          		neo.loss.im[[i]]$IM)/
                              paleo.loss.im[[i]]$IM)) > 1))
            {
                print(sprintf("IM mismatch in LOSS-RATE #%d",
                              i))
                break
            }

        paleo.loss.edp[[i]] <- read.csv(
            sprintf("%sloss_%d_edp.txt", results.dir, i),
            skip=3, header=FALSE, sep="")
        names(paleo.loss.edp[[i]])=c("EDP","mean.x","sd.lnx")

        neo.loss.edp[[i]] <- read.csv(
            sprintf("results/loss_%d_edp.txt", i),
            header=TRUE, sep="")
        names(neo.loss.edp[[i]]) = c("EDP","mean.x","sd.lnx")

        if (length(paleo.loss.edp[[i]]$EDP) != 
            length(neo.loss.edp[[i]]$EDP) ||
            (max(abs((paleo.loss.edp[[i]]$EDP - 
          		neo.loss.edp[[i]]$EDP)/
                              paleo.loss.edp[[i]]$EDP)) > 1))
            {
                print(sprintf("EDP mismatch in LOSS-EDP #%d",
                              i))
                break
            }
    }

    ##Read the Total Loss data:
    paleo.structloss.nc <- read.csv(
        paste(results.dir, "loss_nc_total", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.structloss.nc) = c("IM", "mean.x", "sd.lnx")

    ## Function for comparing data sets, for convenience:
    compare <- function(a, b)  {
        result <-data.frame(Value = c(max(abs(a-b)),
                                mean(abs(a-b)),
                                100 * max(abs(a-b)/a)))
        rownames(result) <- c("max(abs(difference))",
                      	    "mean(abs(difference))",
                      	    "percent(abs(difference))")
        return(result)
    }
  #+END_SRC

  #+RESULTS:


\clearpage
* IM
  Compare the IM rate of exceedence as calculated by both versions:
  #+BEGIN_SRC R :results output latex 
    xtable(compare(paleo.im$lambda, neo.im$lambda)
         , caption="Comparison of IM Rate calculations.",
  	 digits=c(5))
  #+END_SRC

  #+RESULTS:
  #+BEGIN_EXPORT latex
  % latex table generated in R 3.2.2 by xtable 1.8-2 package
  % Mon Aug 29 14:09:31 2016
  \begin{table}[ht]
  \centering
  \begin{tabular}{rr}
    \hline
   & Value \\ 
    \hline
  max(abs(difference)) & 0.00005 \\ 
    mean(abs(difference)) & 0.00000 \\ 
    percent(abs(difference)) & 0.03102 \\ 
     \hline
  \end{tabular}
  \caption{Comparison of IM Rate calculations.} 
  \end{table}
  #+END_EXPORT

  Plot it (Figure [[fig:im-rate]]):
  <<code:im-rate-plot>>
  #+NAME: im-rate
  #+HEADER: :results graphics 
  #+HEADER: :file (org-babel-temp-file "./figure-" ".eps")
  #+BEGIN_SRC R
     palette(c("red", "blue"))
     plot(paleo.im$lambda ~ paleo.im$IM, log="xy", 
  	xlab="IM", ylab="lambda", main="IM Rate",
  	type="l", lwd=3, col=1,
  	xlim=c(0.01, 3.0), ylim=c(1E-8, 1E0),
  	pch=25)

    lines(neo.im$lambda ~ neo.im$IM, lwd=1, col=2)

    legend(x="topright",
  	 legend=c("Paleo", "Neo"),
  	 fill=palette())
  #+END_SRC

  #+RESULTS:
  [[file:/tmp/babel-1782NP6/figure-1782asb.pdf]]

  #+CAPTION: IM rate comparison ([[code:im-rate-plot][code]]).
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:im-rate
  #+RESULTS: im-rate
  [[file:/tmp/babel-1786g10/figure-17869EV.eps]]

\clearpage
* EDP
** Acceleration
*** EDP-IM Relationship
    Compare the mean and standard deviation calculations for the EDP values
    representing acceleration. For each EDP, this table shows the maximum
    absolute difference between the two programs, the mean absolute difference,
    and the maximum percentage difference for both the mean and standard
    deviation calculations:
    #+BEGIN_SRC R :results output latex 
      edp.columns <- data.frame(
          Index=seq(1, num.edps, 1),
          Label=c("Ground Floor Accel",
              "2nd Story Drift", "2nd Story Accel",
              "3rd Floor Drift", "3rd Floor Accel",
              "4th Floor Drift", "4th Floor Accel",
              "5th Floor Drift", "5th Floor Accel",
              "6th Floor Drift", "6th Floor Accel",
              "7th Floor Drift", "7th Floor Accel",
              "8th Floor Drift", "8th Floor Accel",
              "9th Floor Drift", "9th Floor Accel",
              "10th Floor Drift", "10th Floor Accel",
              "Roof Drift", "Roof Accel"),
          stringsAsFactors=FALSE)

      acceleration.cols = edp.columns[seq(1, num.edps, 2),]
      drift.cols = edp.columns[seq(2, num.edps, 2),]

      edp.comparion <- as.data.frame(
          matrix(nrow=length(acceleration.cols$Index), ncol=7),
          stringsasfactors=FALSE)
      names(edp.comparion) <- c("Floor", "mean.max", "mean.avg",
                                "mean.pct", "sd.max", "sd.avg",
                                "sd.pct")

      for (i in 1:nrow(acceleration.cols)) {
          index <- acceleration.cols[i,]$Index
          edp.comparion[i,]$Floor <- acceleration.cols[i,]$Label

          temp <- compare(paleo.edp.im[[index]]$mean.x,
                          neo.edp.im[[index]]$mean.x)

          edp.comparion[i,]$mean.max <- temp[1,]
          edp.comparion[i,]$mean.avg <- temp[2,]
          edp.comparion[i,]$mean.pct <- temp[3,]

          temp <- compare(paleo.edp.im[[index]]$sd.lnx,
                          neo.edp.im[[index]]$sd.lnx)
          edp.comparion[i,]$sd.max <- temp[1,]
          edp.comparion[i,]$sd.avg <- temp[2,]
          edp.comparion[i,]$sd.pct <- temp[3,]
      }
      print(
          xtable(edp.comparion, 
                 caption="Comparison of EDP-IM calculations 
                          for acceleration EDPs.",
                 digits=c(5)),
          include.rownames=FALSE)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:32 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{lrrrrrr}
      \hline
    Floor & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    Ground Floor Accel & 0.00049 & 0.00008 & 0.03987 & 0.00397 & 0.00018 & 1.20267 \\ 
      2nd Story Accel & 0.00049 & 0.00009 & 0.04503 & 0.01882 & 0.00133 & 3.99385 \\ 
      3rd Floor Accel & 0.00049 & 0.00020 & 0.04210 & 0.00826 & 0.00059 & 2.06527 \\ 
      4th Floor Accel & 0.00050 & 0.00003 & 0.04744 & 0.00891 & 0.00053 & 2.41306 \\ 
      5th Floor Accel & 0.00005 & 0.00001 & 0.03843 & 0.00893 & 0.00051 & 2.59785 \\ 
      6th Floor Accel & 0.00005 & 0.00004 & 0.04537 & 0.00817 & 0.00058 & 4.59038 \\ 
      7th Floor Accel & 0.00005 & 0.00004 & 0.02859 & 0.00531 & 0.00045 & 1.96190 \\ 
      8th Floor Accel & 0.00005 & 0.00004 & 0.04259 & 0.00327 & 0.00032 & 2.09343 \\ 
      9th Floor Accel & 0.00005 & 0.00001 & 0.03139 & 0.02046 & 0.00091 & 7.11310 \\ 
      10th Floor Accel & 0.00005 & 0.00004 & 0.02006 & 0.01604 & 0.00057 & 6.07850 \\ 
      Roof Accel & 0.00005 & 0.00004 & 0.01875 & 0.00213 & 0.00021 & 0.85317 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of EDP-IM calculations 
			for acceleration EDPs.} 
    \end{table}
    #+END_EXPORT

    Plot the mean (Figure [[fig:accel-im-mean]]) and standard deviation (Figure [[fig:accel-im-sd-lnx]]):
    <<code:accel-im-mean>>
    #+NAME: accel-im-mean
    #+HEADER: :results graphics 
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(acceleration.cols)))

      x.range <- c()
      y.range <- c()
      for (i in acceleration.cols$Index) {
          x.range <-range(x.range, paleo.edp.im[[i]]$IM)
          y.range <-range(y.range, paleo.edp.im[[i]]$mean.x)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="IM", ylab="Mean Acceleration",
           main="Mean Acceleration vs. IM")

      for (i in 1:nrow(acceleration.cols)) {
          index = acceleration.cols[i,]$Index
          lines(paleo.edp.im[[index]]$mean.x ~
                paleo.edp.im[[index]]$IM, 
                col=i, lwd=3)

          lines(neo.edp.im[[index]]$mean.x ~ 
                neo.edp.im[[index]]$IM, 
                lwd=1)
      }
      legend(x="topleft", legend=acceleration.cols$Label,
    	 fill=palette())
    #+END_SRC

    #+CAPTION: mean(Acceleration EDP) vs. IM ([[code:accel-im-mean][code]]).
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:accel-im-mean
    #+RESULTS: accel-im-mean
    [[file:/tmp/babel-1786g10/figure-1786kjn.pdf]]

    #+NAME: accel-im-sd-lnx
    #+HEADER: :results graphics 
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(acceleration.cols)))

      x.range <- c()
      y.range <- c()
      for (i in acceleration.cols$Index) {
          x.range <-range(x.range, paleo.edp.im[[i]]$IM)
          y.range <-range(y.range, paleo.edp.im[[i]]$sd.lnx)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="IM", ylab="Sd Acceleration",
           main="Sd Acceleration vs. IM")

      for (i in 1:nrow(acceleration.cols)) {
          index = acceleration.cols[i,]$Index
          lines(paleo.edp.im[[index]]$sd.lnx ~ 
                paleo.edp.im[[index]]$IM, 
                col=i, lwd=3)

          lines(neo.edp.im[[index]]$sd.lnx ~ 
                neo.edp.im[[index]]$IM, 
                lwd=1)
      }
      legend(x="topright", legend=acceleration.cols$Label,
    	 fill=palette())
    #+END_SRC

    #+CAPTION: SD(ln(Acceleration EDP)) vs. IM ([[accel-im-sd-lnx][code]])
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:accel-im-sd-lnx
    #+RESULTS: accel-im-sd-lnx
    [[file:/tmp/babel-1786g10/figure-1786wBD.pdf]]

\clearpage
*** Rate Relationship
    Compare the EDP-RATE calculations, for acceleration-type EDPS:
    #+BEGIN_SRC R :results output latex 
      edp.comparion <- as.data.frame(
          matrix(nrow=length(acceleration.cols$Index), ncol=4),
          stringsasfactors=FALSE)

      names(edp.comparion) <- c("Floor", "mean", "avg", "pct")

      for (i in 1:nrow(acceleration.cols)) {
          index <- acceleration.cols[i,]$Index
          edp.comparion[i,]$Floor <- acceleration.cols[i,]$Label

          temp <- compare(paleo.edp.rate[[index]]$lambda,
                          neo.edp.rate[[index]]$lambda)

          edp.comparion[i,]$mean <- temp[1,]
          edp.comparion[i,]$avg <- temp[2,]
          edp.comparion[i,]$pct <- temp[3,]
      }
      print(xtable(edp.comparion,
                   caption="Comparion of EDP-RATE calculations, 
                        for acceleration-type EDPs",
                   digits=5),
        include.rownames=FALSE)
     #+END_SRC

     #+RESULTS:
     #+BEGIN_EXPORT latex
     % latex table generated in R 3.2.2 by xtable 1.8-2 package
     % Mon Aug 29 14:09:32 2016
     \begin{table}[ht]
     \centering
     \begin{tabular}{lrrr}
       \hline
     Floor & mean & avg & pct \\ 
       \hline
     Ground Floor Accel & 0.01078 & 0.00013 & 7.09145 \\ 
       2nd Story Accel & 0.00007 & 0.00001 & 1.11364 \\ 
       3rd Floor Accel & 0.00004 & 0.00001 & 0.67354 \\ 
       4th Floor Accel & 0.00004 & 0.00001 & 1.30972 \\ 
       5th Floor Accel & 0.00004 & 0.00001 & 1.17441 \\ 
       6th Floor Accel & 0.00003 & 0.00000 & 0.56153 \\ 
       7th Floor Accel & 0.00002 & 0.00000 & 0.44723 \\ 
       8th Floor Accel & 0.00013 & 0.00000 & 0.59791 \\ 
       9th Floor Accel & 0.00033 & 0.00001 & 1.42361 \\ 
       10th Floor Accel & 0.00002 & 0.00001 & 1.57324 \\ 
       Roof Accel & 0.00004 & 0.00000 & 0.79889 \\ 
	\hline
     \end{tabular}
     \caption{Comparion of EDP-RATE calculations, 
		       for acceleration-type EDPs} 
     \end{table}
     #+END_EXPORT

     Plot the calculated curves (Figure [[fig:accel-im-lambda]]):
    #+NAME: accel-im-lambda
    #+HEADER: :results graphics 
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(acceleration.cols)))

      x.range <- c()
      y.range <- c()
      for (i in acceleration.cols$Index) {
          x.range <-range(x.range, paleo.edp.rate[[i]]$EDP)
          y.range <-range(y.range, paleo.edp.rate[[i]]$lambda)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="EDP", ylab="Lambda",
           log="y",
           main="Lambda(Acceleration) vs. EDP")

      for (i in 1:nrow(acceleration.cols)) {
          index = acceleration.cols[i,]$Index
          lines(paleo.edp.rate[[index]]$lambda ~
                paleo.edp.rate[[index]]$EDP, col=i, lwd=3)

          lines(neo.edp.rate[[index]]$lambda ~
                neo.edp.rate[[index]]$EDP, lwd=1)
      }
      legend(x="topright", legend=acceleration.cols$Label,
    	 fill=palette())
    #+END_SRC

    #+CAPTION: SD(ln(Acceleration EDP)) vs. IM ([[accel-im-lambda][code]])
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:accel-im-lambda
    #+RESULTS: accel-im-lambda
    [[file:/tmp/babel-1786g10/figure-1786XgV.pdf]]

\clearpage
** Drift   
*** EDP-IM Relationship
    Compare the mean and standard deviation calculations for the EDP values
    representing drift. For each EDP, this table shows the maximum
    absolute difference between the two programs, the mean absolute difference,
    and the maximum percentage difference for both the mean and standard
    deviation calculations:
    #+BEGIN_SRC R :results output latex 
      edp.comparion <- as.data.frame(
          matrix(nrow=length(drift.cols$Index), ncol=7),
          stringsasfactors=FALSE)

      names(edp.comparion) <- c("Floor", "mean.max", "mean.avg",
                                "mean.pct", "sd.max", "sd.avg", 
                                "sd.pct")

      for (i in 1:nrow(drift.cols)) {
          index <- drift.cols[i,]$Index
          edp.comparion[i,]$Floor <- drift.cols[i,]$Label

          temp <- compare(paleo.edp.im[[index]]$mean.x,
                          neo.edp.im[[index]]$mean.x)
          edp.comparion[i,]$mean.max <- temp[1,]
          edp.comparion[i,]$mean.avg <- temp[2,]
          edp.comparion[i,]$mean.pct <- temp[3,]

          temp <- compare(paleo.edp.im[[index]]$sd.lnx,
                          neo.edp.im[[index]]$sd.lnx)
          edp.comparion[i,]$sd.max <- temp[1,]
          edp.comparion[i,]$sd.avg <- temp[2,]
          edp.comparion[i,]$sd.pct <- temp[3,]
      }
      print(xtable(edp.comparion, 
                   caption="Comparison of EDP-IM calculations
    			for drift EDPs.",
                   digits=c(5)),
    	include.rownames=FALSE)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:33 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{lrrrrrr}
      \hline
    Floor & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    2nd Story Drift & 0.00000 & 0.00000 & 0.00379 & 0.17459 & 0.00628 & 33.11192 \\ 
      3rd Floor Drift & 0.00000 & 0.00000 & 0.00300 & 0.16334 & 0.00521 & 29.37046 \\ 
      4th Floor Drift & 0.00000 & 0.00000 & 0.00384 & 0.13388 & 0.00398 & 26.64797 \\ 
      5th Floor Drift & 0.00000 & 0.00000 & 0.00373 & 0.14656 & 0.00414 & 31.22790 \\ 
      6th Floor Drift & 0.00000 & 0.00000 & 0.00299 & 0.15449 & 0.00448 & 33.14727 \\ 
      7th Floor Drift & 0.00000 & 0.00000 & 0.00398 & 0.19776 & 0.00545 & 41.44412 \\ 
      8th Floor Drift & 0.00000 & 0.00000 & 0.00489 & 0.22162 & 0.00716 & 45.24358 \\ 
      9th Floor Drift & 0.00000 & 0.00000 & 0.00456 & 0.04243 & 0.00390 & 11.78909 \\ 
      10th Floor Drift & 0.00000 & 0.00000 & 0.00490 & 0.12022 & 0.00947 & 21.42163 \\ 
      Roof Drift & 0.00000 & 0.00000 & 0.00358 & 0.14249 & 0.00638 & 26.23510 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of EDP-IM calculations
		      for drift EDPs.} 
    \end{table}
    #+END_EXPORT

    Plot the mean (Figure [[fig:drift-im-mean]]) and standard deviation (Figure [[fig:drift-im-sd-lnx]]):
    #+NAME: drift-im-mean
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(drift.cols)))

      x.range <- c()
      y.range <- c()
      for (i in drift.cols$Index) {
          x.range <-range(x.range, paleo.edp.im[[i]]$IM)
          y.range <-range(y.range, paleo.edp.im[[i]]$mean.x)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="IM", ylab="Mean Drift",
           main="Mean Drift vs. IM")

      for (i in 1:nrow(drift.cols)) {
          index = drift.cols[i,]$Index
          lines(paleo.edp.im[[index]]$mean.x ~
                paleo.edp.im[[index]]$IM, col=i, lwd=3)

          lines(neo.edp.im[[index]]$mean.x ~
                neo.edp.im[[index]]$IM, lwd=1)
      }
      legend(x="topleft", legend=drift.cols$Label,
    	 fill=palette())
    #+END_SRC

    #+CAPTION: mean(Drift EDP) vs. IM ([[drift-im-mean][code]]).
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:drift-im-mean
    #+RESULTS: drift-im-mean
    [[file:/tmp/babel-1786g10/figure-1786--n.pdf]]

    #+NAME: drift-im-sd-lnx
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(drift.cols)))

      x.range <- c()
      y.range <- c()
      for (i in drift.cols$Index) {
          x.range <-range(x.range, paleo.edp.im[[i]]$IM)
          y.range <-range(y.range, paleo.edp.im[[i]]$sd.lnx)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="IM", ylab="Sd Drift",
           main="Sd Drift vs. IM")

      for (i in 1:nrow(drift.cols)) {
          index = drift.cols[i,]$Index
          lines(paleo.edp.im[[index]]$sd.lnx ~
                paleo.edp.im[[index]]$IM, col=i, lwd=3)

          lines(neo.edp.im[[index]]$sd.lnx ~
                neo.edp.im[[index]]$IM, lwd=1)
      }
      legend(x="topright", legend=drift.cols$Label, 
    	 fill=palette())
    #+END_SRC

    #+CAPTION: SD(ln(Drift EDP)) vs. IM ([[drift-im-sd-lnx][code]])
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:drift-im-sd-lnx
    #+RESULTS: drift-im-sd-lnx
    [[file:/tmp/babel-1786g10/figure-1786KdD.pdf]]

\clearpage
*** Rate Relationship
    Compare the EDP-RATE calculations, for drift-type EDPS:
    #+BEGIN_SRC R :results output latex
      edp.comparion <- as.data.frame(
          matrix(nrow=length(drift.cols$Index), ncol=4),
          stringsasfactors=FALSE)

      names(edp.comparion) <- c("Floor", "mean", "avg", "pct")

      for (i in 1:nrow(drift.cols)) {
          index <- drift.cols[i,]$Index
          edp.comparion[i,]$Floor <- drift.cols[i,]$Label

          temp <- compare(paleo.edp.rate[[index]]$lambda,
                          neo.edp.rate[[index]]$lambda)
          edp.comparion[i,]$mean <- temp[1,]
          edp.comparion[i,]$avg <- temp[2,]
          edp.comparion[i,]$pct <- temp[3,]
      }
      print(xtable(edp.comparion,
                   caption="Comparion of EDP-RATE calculations,
    			for drift-type EDPs",
                   digits=5),
    	include.rownames=FALSE)
     #+END_SRC

     #+RESULTS:
     #+BEGIN_EXPORT latex
     % latex table generated in R 3.2.2 by xtable 1.8-2 package
     % Mon Aug 29 14:09:33 2016
     \begin{table}[ht]
     \centering
     \begin{tabular}{lrrr}
       \hline
     Floor & mean & avg & pct \\ 
       \hline
     2nd Story Drift & 0.00020 & 0.00002 & 3.10339 \\ 
       3rd Floor Drift & 0.00026 & 0.00005 & 2.42177 \\ 
       4th Floor Drift & 0.00014 & 0.00004 & 2.37060 \\ 
       5th Floor Drift & 0.00012 & 0.00004 & 4.84768 \\ 
       6th Floor Drift & 0.00013 & 0.00004 & 3.30381 \\ 
       7th Floor Drift & 0.00016 & 0.00005 & 3.96479 \\ 
       8th Floor Drift & 0.00021 & 0.00006 & 4.17732 \\ 
       9th Floor Drift & 0.00008 & 0.00001 & 1.70680 \\ 
       10th Floor Drift & 0.00005 & 0.00001 & 1.56145 \\ 
       Roof Drift & 0.00002 & 0.00000 & 1.19716 \\ 
	\hline
     \end{tabular}
     \caption{Comparion of EDP-RATE calculations,
		       for drift-type EDPs} 
     \end{table}
     #+END_EXPORT

     Plot the calculated curves (Figure [[fig:drift-im-lambda]]):
    #+NAME: drift-im-lambda
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      palette(rainbow(nrow(drift.cols)))

      x.range <- c()
      y.range <- c()
      for (i in drift.cols$Index) {
          x.range <-range(x.range, paleo.edp.rate[[i]]$EDP)
          y.range <-range(y.range, paleo.edp.rate[[i]]$lambda)
      }
      plot(NULL, xlim=x.range, ylim=y.range, 
           xlab="EDP", ylab="Lambda",
           log="y",
           main="Lambda(Drift) vs. EDP")

      for (i in 1:nrow(drift.cols)) {
          index = drift.cols[i,]$Index
          lines(paleo.edp.rate[[index]]$lambda ~ 
                paleo.edp.rate[[index]]$EDP, col=i, lwd=3)

          lines(neo.edp.rate[[index]]$lambda ~ 
                neo.edp.rate[[index]]$EDP, lwd=1)
      }
      legend(x="topright", legend=drift.cols$Label, 
    	 fill=palette())
    #+END_SRC

    #+CAPTION: SD(ln(Drift EDP)) vs. IM ([[drift-im-lambda][code]])
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:drift-im-lambda
    #+RESULTS: drift-im-lambda
    [[file:/tmp/babel-1786g10/figure-1786x7V.pdf]]
\clearpage
* COLLAPSE
  Compare the two versions:
  #+BEGIN_SRC R :results output latex
    xtable(compare(paleo.collapse.im$pCollapse,
    	       neo.collapse.im$pCollapse),
  	 caption="Comparison of Collapse-IM calculations.",
  	 digits=c(5))
  #+END_SRC

  #+RESULTS:
  #+BEGIN_EXPORT latex
  % latex table generated in R 3.2.2 by xtable 1.8-2 package
  % Mon Aug 29 14:09:34 2016
  \begin{table}[ht]
  \centering
  \begin{tabular}{rr}
    \hline
   & Value \\ 
    \hline
  max(abs(difference)) & 0.24039 \\ 
    mean(abs(difference)) & 0.09745 \\ 
    percent(abs(difference)) &    Inf \\ 
     \hline
  \end{tabular}
  \caption{Comparison of Collapse-IM calculations.} 
  \end{table}
  #+END_EXPORT

  Plot it the collapse curves:
  #+NAME: collapse-im
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM, 
         log="", lwd=5,
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
        col=2, lwd=3)

    lines(neo.collapse.im$pDemolition ~ neo.collapse.im$IM, 
        col=3, lwd=3)

    legend(x="right",
         legend=c("Paleo", "Neo", "Neo Demo"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Probability of Collapse calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im
  #+RESULTS: collapse-im
  [[file:/tmp/babel-1786g10/figure-1786Yao.pdf]]

  The overall rate of collapse:
  #+BEGIN_SRC R  :results value 
    paleo.rate <- scan(paste(results.dir, "collrate.txt", 
                             sep=""), skip=3)
    neo.rate <- as.numeric(scan("results/collrate.txt", 
                                what="string")[8])
    paste(
        sprintf("Paleo: %5.3e; Neo: %5.3e; error: %3.2f%%", 
                paleo.rate,
                neo.rate, 
                (100*abs(neo.rate - paleo.rate)/paleo.rate)),
        sep="\n")
  #+END_SRC
  
  #+RESULTS:
  : Paleo: 2.159e-04; Neo:    NA; error:  NA%

\clearpage
* Component Groups
  #+BEGIN_SRC R :results output latex 
    ## This data comes from the old Example 2 input file, desc
    ## ribing the component groups:
    cgs.descrip <- data.frame(

        matrix( c(1, 2, 2, 20, 2, 2, 2, 18, 3, 2, 4, 4, 4,
    2, 4, 18, 5, 2, 6, 4, 6, 2, 6, 18, 7, 2, 8, 4, 8, 2, 8,
    18, 9, 2, 10, 4, 10, 2, 10, 18, 11, 2, 12, 4, 12, 2,
    12, 18, 13, 2, 14, 4, 14, 2, 14, 18, 15, 2, 16, 4, 16,
    2, 16, 18, 17, 2, 18, 4, 18, 2, 18, 18, 19, 2, 20, 4,
    20, 2, 20, 18, 21, 3, 2, 16, 22, 3, 4, 16, 23, 3, 6,
    16, 24, 3, 8, 16, 25, 3, 10, 16, 26, 3, 12, 16, 27, 3,
    14, 16, 28, 3, 16, 16, 29, 3, 18, 16, 30, 3, 20, 16,
    31, 105, 2, 721, 32, 105, 4, 721, 33, 105, 6, 721, 34,
    105, 8, 721, 35, 105, 10, 721, 36, 105, 12, 721, 37,
    105, 14, 721, 38, 105, 16, 721, 39, 105, 18, 721, 40,
    105, 20, 721, 41, 107, 2, 99, 42, 107, 4, 99, 43, 107,
    6, 99, 44, 107, 8, 99, 45, 107, 10, 99, 46, 107, 12,
    99, 47, 107, 14, 99, 48, 107, 16, 99, 49, 107, 18, 99,
    50, 107, 20, 99, 51, 203, 3, 693, 52, 203, 5, 693, 53,
    203, 7, 693, 54, 203, 9, 693, 55, 203, 11, 693, 56,
    203, 13, 693, 57, 203, 15, 693, 58, 203, 17, 693, 59,
    203, 19, 693, 60, 203, 21, 693, 61, 211, 3, 23, 62,
    211, 5, 23, 63, 211, 7, 23, 64, 211, 9, 23, 65, 211,
    11, 23, 66, 211, 13, 23, 67, 211, 15, 23, 68, 211, 17,
    23, 69, 211, 19, 23, 70, 211, 21, 23, 71, 208, 1, 53,
    72, 208, 3, 53, 73, 208, 5, 53, 74, 208, 7, 53, 75,
    208, 9, 53, 76, 208, 11, 53, 77, 208, 13, 53, 78, 208,
    15, 53, 79, 208, 17, 53, 80, 208, 19, 53, 81, 209, 5,
    16, 82, 209, 11, 16, 83, 209, 19, 16, 84, 205, 21, 4,
    85, 204, 1, 2, 86, 106, 2, 721, 87, 106, 4, 721, 88,
    106, 6, 721, 89, 106, 8, 721, 90, 106, 10, 721, 91,
    106, 12, 721, 92, 106, 14, 721, 93, 106, 16, 721, 94,
    106, 18, 721, 95, 106, 20, 721, 96, 108, 2, 10, 97,
    108, 4, 10, 98, 108, 6, 10, 99, 108, 8, 10, 100, 108,
    10, 10, 101, 108, 12, 10, 102, 108, 14, 10, 103, 108,
    16, 10, 104, 108, 18, 10, 105, 108, 20, 10, 106, 214,
    1, 10, 107, 214, 3, 10, 108, 214, 5, 10, 109, 214, 7,
    10, 110, 214, 9, 10, 111, 214, 11, 10, 112, 214, 13,
    10, 113, 214, 15, 10, 114, 214, 17, 10, 115, 214, 19,
    10),
               ncol=4, byrow=TRUE) )

    names(cgs.descrip) <- c("Index","Type","EDP","Quantity") 
    component.types <- levels(factor(cgs.descrip$Type))
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT latex
#+END_EXPORT

** Loss-EDP Relation
   #+BEGIN_SRC R :results output latex 
     ## This data comes from the old Example 2 input file, desc
     ## ribing the component groups:
     cg.edp.summary <- as.data.frame(matrix(nrow=num.cgs,
   					 ncol=6))
     names(cg.edp.summary) <- c("mean.max", "mean.avg",
                                "mean.pct", "sd.max", 
                                "sd.avg", "sd.pct")

     for (i in 1:num.cgs) {
         temp <- compare(paleo.loss.edp[[i]]$mean.x, 
                         neo.loss.edp[[i]]$mean.x)
         cg.edp.summary[i,]$mean.max <- temp[1,]
         cg.edp.summary[i,]$mean.avg <- temp[2,]
         cg.edp.summary[i,]$mean.pct <- temp[3,]

         temp <- compare(paleo.loss.edp[[i]]$sd.lnx,
                         neo.loss.edp[[i]]$sd.lnx)
         cg.edp.summary[i,]$sd.max <- temp[1,]
         cg.edp.summary[i,]$sd.avg <- temp[2,]
         cg.edp.summary[i,]$sd.pct <- temp[3,]
     }
   #+END_SRC

   #+RESULTS:
   #+BEGIN_EXPORT latex
#+END_EXPORT

    
   #+BEGIN_SRC R :results output 
    ## Function to print summary table of  group-EDP relations
    print.cg.edp.summary <- function(CG) {
        print(
            xtable(
                cg.edp.summary[cgs.descrip
  			 [cgs.descrip$Type==CG,]$Index,],
                caption=sprintf("Comparison of Component
    			      Groups of type #%s.", CG),
                digits=3))
    }
   #+END_SRC

   #+RESULTS:

   #+BEGIN_SRC R :results output 
    ## Function to plot component group-EDP relations
    plot_cg_edp <- function(CG) {
        par(mfrow=c(2,1))
        components<-cgs.descrip[cgs.descrip$Type == CG,]$Index
        palette(rainbow(max(length(components), 2)))

        x.range <- c()
        y.range <- c()
        for (c in components) {
            x.range<-range(x.range, paleo.loss.edp[[c]]$EDP)
            y.range<-range(y.range,paleo.loss.edp[[c]]$mean.x)

            x.range<-range(x.range, neo.loss.edp[[c]]$EDP)
            y.range<-range(y.range,neo.loss.edp[[c]]$mean.x)
        }
        plot(NULL, xlim=x.range, ylim=y.range, 
             xlab="EDP", ylab="Mean(Loss)",
             log="",
             main=sprintf("Mean(Loss) vs. EDP, Component #%d", 
                 CG))

        for (i in 1:length(components)) {
            index = components[i]
            lines(paleo.loss.edp[[index]]$mean.x ~ 
  		paleo.loss.edp[[index]]$EDP, 
  		col=i, lwd=3)

            lines(neo.loss.edp[[index]]$mean.x ~ 
  		neo.loss.edp[[index]]$EDP, lwd=1)
        }

        x.range <- c()
        y.range <- c()
        for (c in components) {
            x.range<-range(x.range,paleo.loss.edp[[c]]$EDP)
            y.range<-range(y.range,paleo.loss.edp[[c]]$sd.lnx)

            x.range<-range(x.range,neo.loss.edp[[c]]$EDP)
            y.range<-range(y.range,neo.loss.edp[[c]]$sd.lnx)
        }
        plot(NULL, xlim=x.range, ylim=y.range, 
             xlab="EDP", ylab="SD(ln(Loss))",
             log="",
             main=sprintf(
                 "SD(ln(Loss)) vs. EDP, Component #%d",
                 CG))

        for (i in 1:length(components)) {
            index = components[i]
            lines(paleo.loss.edp[[index]]$sd.lnx ~
  		paleo.loss.edp[[index]]$EDP,
  		col=i, lwd=3)

            lines(neo.loss.edp[[index]]$sd.lnx ~ 
  		neo.loss.edp[[index]]$EDP, 
  		lwd=1)
        }
        legend(x="topright", legend=components, fill=palette(), 
               ncol=4)
    }
   #+END_SRC

   #+RESULTS:

   \clearpage
*** Component Type #2
    #+BEGIN_SRC R :results output latex 
      CG = 2
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:35 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    1 & 0.500 & 0.239 & 0.017 & 0.000 & 0.000 & 0.025 \\ 
      2 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      3 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      4 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      5 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      6 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      7 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      8 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      9 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      10 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      11 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      12 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      13 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      14 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      15 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      16 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      17 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      18 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
      19 & 0.500 & 0.235 & 0.036 & 0.000 & 0.000 & 0.025 \\ 
      20 & 0.500 & 0.251 & 0.031 & 0.000 & 0.000 & 0.025 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #2.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-2-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(2)
    #+END_SRC

    #+CAPTION: Components of type #2
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-2-edp
    #+RESULTS: cg-2-edp
    [[file:/tmp/babel-1786g10/figure-1786-MQ.pdf]]

    \clearpage
*** Component Type #3
    #+BEGIN_SRC R :results output latex 
      CG = 3
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:35 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    21 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      22 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      23 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      24 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      25 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      26 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      27 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      28 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      29 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
      30 & 1119.080 & 24.029 & 14.043 & 0.327 & 0.009 & 33.369 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #3.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-3-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #3
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-3-edp
    #+RESULTS: cg-3-edp
    [[file:/tmp/babel-1786g10/figure-1786lri.pdf]]

    \clearpage
*** Component Type #105
    #+BEGIN_SRC R :results output latex 
      CG = 105
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:36 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    31 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      32 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      33 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      34 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      35 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      36 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      37 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      38 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      39 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
      40 & 5.000 & 2.609 & 1.271 & 0.001 & 0.000 & 0.022 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #105.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-105-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #105
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-105-edp
    #+RESULTS: cg-105-edp
    [[file:/tmp/babel-1786g10/figure-1786MK1.pdf]]

    \clearpage
*** Component Type #106
    #+BEGIN_SRC R :results output latex 
      CG = 106
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:36 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    86 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      87 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      88 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      89 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      90 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      91 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      92 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      93 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      94 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
      95 & 6057.630 & 71.263 & 63.384 & 0.609 & 0.008 & 236.151 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #106.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-106-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #106
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-106-edp
    #+RESULTS: cg-106-edp
    [[file:/tmp/babel-1786g10/figure-1786YoQ.pdf]]

    \clearpage
*** Component Type #107
    #+BEGIN_SRC R :results output latex 
      CG = 107
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:36 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    41 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      42 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      43 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      44 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      45 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      46 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      47 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      48 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      49 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
      50 & 0.500 & 0.203 &  Inf & 7.347 & 0.070 &  Inf \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #107.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-107-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #107
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-107-edp
    #+RESULTS: cg-107-edp
    [[file:/tmp/babel-1786g10/figure-1786_Gj.pdf]]

    \clearpage
*** Component Type #108
    #+BEGIN_SRC R :results output latex 
      CG = 108
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:37 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    96 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      97 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      98 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      99 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      100 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      101 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      102 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      103 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      104 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
      105 & 0.500 & 0.233 & 0.036 & 0.000 & 0.000 & 0.048 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #108.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-108-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #108
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-108-edp
    #+RESULTS: cg-108-edp
    [[file:/tmp/babel-1786g10/figure-1786ml1.pdf]]

    \clearpage
*** Component Type #203
    #+BEGIN_SRC R :results output latex 
      CG = 203
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:37 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    51 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      52 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      53 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      54 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      55 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      56 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      57 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      58 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      59 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
      60 & 23.000 & 14.815 & 0.038 & 0.001 & 0.000 & 0.042 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #203.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-203-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #203
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-203-edp
    #+RESULTS: cg-203-edp
    [[file:/tmp/babel-1786g10/figure-1786yDR.pdf]]

    \clearpage
*** Component Type #204
    #+BEGIN_SRC R :results output latex 
      CG = 204
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:37 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    85 & 0.000 & 0.000 & 49.437 & 0.033 & 0.019 & 0.533 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #204.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-204-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #204
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-204-edp
    #+RESULTS: cg-204-edp
    [[file:/tmp/babel-1786g10/figure-1786Zij.pdf]]

    \clearpage
*** Component Type #205
    #+BEGIN_SRC R :results output latex 
      CG = 205
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:38 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    84 & 5.000 & 2.307 & 0.020 & 0.000 & 0.000 & 0.039 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #205.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-205-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #205
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-205-edp
    #+RESULTS: cg-205-edp
    [[file:/tmp/babel-1786g10/figure-1786AB2.pdf]]

    \clearpage
*** Component Type #208
    #+BEGIN_SRC R :results output latex 
      CG = 208
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:38 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    71 & 0.000 & 0.000 & 0.001 & 0.000 & 0.000 & 0.011 \\ 
      72 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      73 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      74 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      75 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      76 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      77 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      78 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      79 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
      80 & 0.500 & 0.230 & 0.028 & 0.000 & 0.000 & 0.041 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #208.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-208-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #208
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-208-edp
    #+RESULTS: cg-208-edp
    [[file:/tmp/babel-1786g10/figure-1786MfR.pdf]]

    \clearpage
*** Component Type #209
    #+BEGIN_SRC R :results output latex 
      CG = 209
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:38 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    81 & 5.000 & 2.279 & 0.028 & 0.000 & 0.000 & 0.042 \\ 
      82 & 5.000 & 2.279 & 0.028 & 0.000 & 0.000 & 0.042 \\ 
      83 & 5.000 & 2.279 & 0.028 & 0.000 & 0.000 & 0.042 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #209.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-209-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #209
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-209-edp
    #+RESULTS: cg-209-edp
    [[file:/tmp/babel-1786g10/figure-1786z9j.pdf]]

    \clearpage
*** Component Type #211
    #+BEGIN_SRC R :results output latex 
      CG = 211
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:39 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    61 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      62 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      63 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      64 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      65 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      66 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      67 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      68 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      69 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
      70 & 0.500 & 0.196 & 0.046 & 0.001 & 0.000 & 0.031 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #211.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-211-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #211
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-211-edp
    #+RESULTS: cg-211-edp
    [[file:/tmp/babel-1786g10/figure-1786ac2.pdf]]

    \clearpage
*** Component Type #214
    #+BEGIN_SRC R :results output latex 
      CG = 214
      print.cg.edp.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:39 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    106 & 0.000 & 0.000 & 0.026 & 0.000 & 0.000 & 0.018 \\ 
      107 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      108 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      109 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      110 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      111 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      112 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      113 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      114 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
      115 & 0.500 & 0.248 & 0.032 & 0.000 & 0.000 & 0.047 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #214.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-214-edp
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_edp(CG)
    #+END_SRC

    #+CAPTION: Components of type #214
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-214-edp
    #+RESULTS: cg-214-edp
    [[file:/tmp/babel-1786g10/figure-1786m6R.pdf]]

    \clearpage
** Loss-IM Relation
  #+BEGIN_SRC R :results output latex 
    cg.im.summary <- as.data.frame(matrix(nrow=num.cgs, 
  					ncol=6))
    names(cg.im.summary) <- c("mean.max", "mean.avg", 
                              "mean.pct", "sd.max", 
                              "sd.avg", "sd.pct")

    for (i in 1:num.cgs) {
        temp <- compare(paleo.loss.im[[i]]$mean.x, 
                        neo.loss.im[[i]]$mean.x)
        cg.im.summary[i,]$mean.max <- temp[1,]
        cg.im.summary[i,]$mean.avg <- temp[2,]
        cg.im.summary[i,]$mean.pct <- temp[3,]

        temp <- compare(paleo.loss.im[[i]]$sd.lnx,
                        neo.loss.im[[i]]$sd.lnx)
        cg.im.summary[i,]$sd.max <- temp[1,]
        cg.im.summary[i,]$sd.avg <- temp[2,]
        cg.im.summary[i,]$sd.pct <- temp[3,]
    }
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT latex
#+END_EXPORT

    
  #+BEGIN_SRC R :results output 
    ## Function to print summary table of  group-IM relations
    print.cg.im.summary <- function(CG) {
        print(
            xtable(
                cg.im.summary[cgs.descrip
  			 [cgs.descrip$Type==CG,]$Index,],
                caption=sprintf("Comparison of Component
    			      Groups of type #%s.", CG),
                digits=3))
    }
    #+END_SRC

    #+RESULTS:

  #+BEGIN_SRC R :results output 
    ## Function to plot component group-IM relations
    plot_cg_im <- function(CG) {
        par(mfrow=c(2,1))
        components<-cgs.descrip[cgs.descrip$Type == CG,]$Index
        palette(rainbow(max(length(components), 2)))

        x.range <- c()
        y.range <- c()
        for (c in components) {
            x.range<-range(x.range, paleo.loss.im[[c]]$IM)
            y.range<-range(y.range,paleo.loss.im[[c]]$mean.x)

            x.range<-range(x.range, neo.loss.im[[c]]$IM)
            y.range<-range(y.range,neo.loss.im[[c]]$mean.x)
        }
        plot(NULL, xlim=x.range, ylim=y.range, 
             xlab="IM", ylab="Mean(Loss)",
             log="",
             main=sprintf("Mean(Loss) vs. IM, Component #%d", 
                 CG))

        for (i in 1:length(components)) {
            index = components[i]
            lines(paleo.loss.im[[index]]$mean.x ~ 
  		paleo.loss.im[[index]]$IM, 
  		col=i, lwd=3)

            lines(neo.loss.im[[index]]$mean.x ~ 
  		neo.loss.im[[index]]$IM, lwd=1)
        }

        x.range <- c()
        y.range <- c()
        for (c in components) {
            x.range<-range(x.range,paleo.loss.im[[c]]$IM)
            y.range<-range(y.range,paleo.loss.im[[c]]$sd.lnx)

            x.range<-range(x.range,neo.loss.im[[c]]$IM)
            y.range<-range(y.range,neo.loss.im[[c]]$sd.lnx)
        }
        plot(NULL, xlim=x.range, ylim=y.range, 
             xlab="IM", ylab="SD(ln(Loss))",
             log="",
             main=sprintf(
                 "SD(ln(Loss)) vs. IM, Component #%d",
                 CG))

        for (i in 1:length(components)) {
            index = components[i]
            lines(paleo.loss.im[[index]]$sd.lnx ~
  		paleo.loss.im[[index]]$IM,
  		col=i, lwd=3)

            lines(neo.loss.im[[index]]$sd.lnx ~ 
  		neo.loss.im[[index]]$IM, 
  		lwd=1)
        }
        legend(x="topright", legend=components, fill=palette(), 
               ncol=4)
    }
  #+END_SRC

  #+RESULTS:

\clearpage
*** Component Type #2
    #+BEGIN_SRC R :results output latex 
      CG = 2
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:40 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    1 & 790.210 & 51.826 & 100.000 & 6.731 & 0.063 & 100.000 \\ 
      2 & 711.190 & 46.679 & 100.000 & 6.731 & 0.063 & 100.000 \\ 
      3 & 397.210 & 12.940 & 100.000 & 5.374 & 0.029 & 100.000 \\ 
      4 & 1786.900 & 57.652 & 100.000 & 5.374 & 0.029 & 100.000 \\ 
      5 & 416.970 & 11.720 & 5.781 & 0.055 & 0.001 & 6.326 \\ 
      6 & 1875.900 & 52.352 & 5.779 & 0.055 & 0.001 & 6.326 \\ 
      7 & 527.720 & 14.330 & 6.631 & 0.063 & 0.002 & 7.828 \\ 
      8 & 2374.700 & 64.124 & 6.625 & 0.063 & 0.002 & 7.828 \\ 
      9 & 545.270 & 15.356 & 6.919 & 0.066 & 0.002 & 8.115 \\ 
      10 & 2451.700 & 68.554 & 6.921 & 0.066 & 0.002 & 8.115 \\ 
      11 & 563.710 & 15.873 & 8.302 & 0.077 & 0.002 & 8.667 \\ 
      12 & 2535.700 & 71.246 & 8.299 & 0.077 & 0.002 & 8.667 \\ 
      13 & 220.160 & 14.734 & 100.000 & 5.444 & 0.029 & 100.000 \\ 
      14 & 991.200 & 65.557 & 100.000 & 5.444 & 0.029 & 100.000 \\ 
      15 & 89.000 & 9.342 & 100.000 & 5.943 & 0.031 & 100.000 \\ 
      16 & 397.800 & 41.180 & 100.000 & 5.943 & 0.031 & 100.000 \\ 
      17 & 248.740 & 10.579 & 100.000 & 6.365 & 0.059 & 100.000 \\ 
      18 & 1120.300 & 47.493 & 100.000 & 6.365 & 0.059 & 100.000 \\ 
      19 & 118.730 & 4.516 &  & 5.455 & 0.053 &  \\ 
      20 & 532.800 & 20.089 &  & 5.455 & 0.053 &  \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #2.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-2-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(2)
    #+END_SRC

    #+CAPTION: Components of type #2
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-2-im
    #+RESULTS: cg-2-im
    [[file:/tmp/babel-1786g10/figure-1786NZk.pdf]]

\clearpage
*** Component Type #3
    #+BEGIN_SRC R :results output latex 
      CG = 3
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:40 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    21 & 5994.900 & 165.588 & 100.000 & 6.504 & 0.065 & 100.000 \\ 
      22 & 1026.300 & 63.790 & 100.000 & 5.153 & 0.034 & 100.000 \\ 
      23 & 1180.800 & 56.049 & 51.086 & 0.188 & 0.009 & 13.527 \\ 
      24 & 1768.900 & 70.927 & 29.668 & 0.183 & 0.009 & 12.894 \\ 
      25 & 1808.100 & 76.188 & 32.773 & 0.179 & 0.009 & 12.917 \\ 
      26 & 1635.800 & 74.745 & 66.848 & 0.185 & 0.010 & 13.384 \\ 
      27 & 1396.450 & 108.165 & 100.000 & 5.224 & 0.036 & 100.000 \\ 
      28 & 573.600 & 158.956 & 100.000 & 5.725 & 0.040 & 100.000 \\ 
      29 & 810.900 & 409.300 & 100.000 & 6.149 & 0.084 & 100.000 \\ 
      30 & 1042.910 & 271.817 & 100.000 & 6.704 & 0.154 & 100.000 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #3.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-3-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #3
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-3-im
    #+RESULTS: cg-3-im
    [[file:/tmp/babel-1786g10/figure-1786032.pdf]]

\clearpage
*** Component Type #105
    #+BEGIN_SRC R :results output latex 
      CG = 105
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:40 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    31 & 1553.090 & 101.876 &  & 0.157 & 0.005 &  \\ 
      32 & 4334.200 & 128.597 &  & 0.066 & 0.002 &  \\ 
      33 & 5055.800 & 122.533 &  Inf & 6.758 & 0.036 &  Inf \\ 
      34 & 6852.900 & 154.284 & 20.925 & 0.063 & 0.002 & 9.211 \\ 
      35 & 6996.600 & 164.143 & 28.465 & 0.065 & 0.002 & 9.370 \\ 
      36 & 6497.700 & 164.619 &  Inf & 6.904 & 0.037 &  Inf \\ 
      37 & 2884.800 & 169.056 &  & 0.059 & 0.003 &  \\ 
      38 & 1194.000 & 106.950 &  & 0.031 & 0.002 &  \\ 
      39 & 3023.200 & 124.104 &  & 0.040 & 0.003 &  \\ 
      40 & 1589.500 & 53.270 &  & 0.048 & 0.003 &  \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #105.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-105-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #105
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-105-im
    #+RESULTS: cg-105-im
    [[file:/tmp/babel-1786g10/figure-1786AWS.pdf]]

\clearpage
*** Component Type #106
    #+BEGIN_SRC R :results output latex 
      CG = 106
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:41 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    86 & 670.470 & 284.752 &  & 0.104 & 0.039 &  \\ 
      87 & 2204.190 & 94.940 &  & 0.207 & 0.013 &  \\ 
      88 & 2081.210 & 106.217 &  Inf & 6.758 & 0.049 &  Inf \\ 
      89 & 2112.330 & 107.810 & 45.282 & 0.217 & 0.015 & 65.597 \\ 
      90 & 2133.530 & 108.683 & 45.127 & 0.226 & 0.016 & 66.089 \\ 
      91 & 2630.390 & 124.718 &  Inf & 6.904 & 0.053 &  Inf \\ 
      92 & 2257.740 & 200.249 &  & 0.216 & 0.026 &  \\ 
      93 & 1175.610 & 400.180 &  & 0.150 & 0.053 &  \\ 
      94 & 1456.600 & 1024.182 &  & 0.180 & 0.127 &  \\ 
      95 & 1971.430 & 1231.422 &  & 0.197 & 0.137 &  \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #106.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-106-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #106
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-106-im
    #+RESULTS: cg-106-im
    [[file:/tmp/babel-1786g10/figure-1786n0k.pdf]]

\clearpage
*** Component Type #107
    #+BEGIN_SRC R :results output latex 
      CG = 107
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:41 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    41 & 20.854 & 1.106 &  & 7.162 & 0.084 &  \\ 
      42 & 94.794 & 2.475 &  & 6.902 & 0.043 &  \\ 
      43 & 93.832 & 2.459 &  & 6.987 & 0.041 &  \\ 
      44 & 127.242 & 2.960 &  & 0.261 & 0.006 &  \\ 
      45 & 130.490 & 3.493 &  & 6.790 & 0.040 &  \\ 
      46 & 131.607 & 3.382 &  & 7.109 & 0.043 &  \\ 
      47 & 67.440 & 4.440 &  & 6.961 & 0.046 &  \\ 
      48 & 29.390 & 2.318 &  & 7.071 & 0.043 &  \\ 
      49 & 46.431 & 2.044 &  & 7.126 & 0.086 &  \\ 
      50 & 38.086 & 0.780 &  & 7.086 & 0.118 &  \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #107.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-107-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #107
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-107-im
    #+RESULTS: cg-107-im
    [[file:/tmp/babel-1786g10/figure-1786zSA.pdf]]

\clearpage
*** Component Type #108
    #+BEGIN_SRC R :results output latex 
      CG = 108
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:41 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    96 & 162.247 & 12.700 & 100.000 & 5.292 & 0.049 & 100.000 \\ 
      97 & 313.890 & 14.064 & 100.000 & 4.276 & 0.024 & 100.000 \\ 
      98 & 279.220 & 11.283 & 3.607 & 0.081 & 0.002 & 6.472 \\ 
      99 & 331.080 & 13.741 & 3.624 & 0.084 & 0.002 & 6.867 \\ 
      100 & 344.020 & 14.622 & 3.869 & 0.090 & 0.002 & 7.380 \\ 
      101 & 395.500 & 13.595 & 5.528 & 0.123 & 0.002 & 9.830 \\ 
      102 & 355.130 & 14.359 & 100.000 & 4.345 & 0.025 & 100.000 \\ 
      103 & 59.210 & 5.519 & 100.000 & 4.684 & 0.025 & 100.000 \\ 
      104 & 181.940 & 14.049 & 100.000 & 5.011 & 0.049 & 100.000 \\ 
      105 & 230.040 & 8.207 & 100.000 & 5.448 & 0.071 & 100.000 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #108.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-108-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #108
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-108-im
    #+RESULTS: cg-108-im
    [[file:/tmp/babel-1786g10/figure-1786axS.pdf]]

\clearpage
*** Component Type #203
    #+BEGIN_SRC R :results output latex 
      CG = 203
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:42 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    51 & 759.000 & 75.831 & 1.995 & 0.004 & 0.000 & 0.598 \\ 
      52 & 249.000 & 27.941 & 3.715 & 0.004 & 0.000 & 0.221 \\ 
      53 & 94.050 & 13.817 & 4.077 & 0.004 & 0.000 & 0.199 \\ 
      54 & 79.980 & 10.675 & 4.313 & 0.005 & 0.000 & 0.248 \\ 
      55 & 209.000 & 11.919 & 1.123 & 0.002 & 0.000 & 0.179 \\ 
      56 & 78.940 & 8.088 & 1.410 & 0.002 & 0.000 & 0.096 \\ 
      57 & 69.100 & 6.570 & 1.076 & 0.002 & 0.000 & 0.088 \\ 
      58 & 323.490 & 14.199 & 5.881 & 0.003 & 0.000 & 0.190 \\ 
      59 & 219.430 & 10.138 & 4.602 & 0.003 & 0.000 & 0.156 \\ 
      60 & 39.700 & 4.841 & 0.525 & 0.001 & 0.000 & 0.080 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #203.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-203-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #203
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-203-im
    #+RESULTS: cg-203-im
    [[file:/tmp/babel-1786g10/figure-1786BQl.pdf]]

\clearpage
*** Component Type #204
    #+BEGIN_SRC R :results output latex 
      CG = 204
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:42 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    85 & 65.000 & 5.149 & 0.065 & 0.001 & 0.000 & 0.249 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #204.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-204-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #204
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-204-im
    #+RESULTS: cg-204-im
    [[file:/tmp/babel-1786g10/figure-1786NuA.pdf]]

\clearpage
*** Component Type #205
    #+BEGIN_SRC R :results output latex 
      CG = 205
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:42 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    84 & 66.900 & 6.855 & 1.096 & 0.002 & 0.000 & 0.090 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #205.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-205-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #205
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-205-im
    #+RESULTS: cg-205-im
    [[file:/tmp/babel-1786g10/figure-17860MT.pdf]]

\clearpage
*** Component Type #208
    #+BEGIN_SRC R :results output latex 
      CG = 208
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:43 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    71 & 105.600 & 3.787 & 0.172 & 0.001 & 0.000 & 0.149 \\ 
      72 & 248.500 & 23.961 & 1.505 & 0.005 & 0.000 & 0.346 \\ 
      73 & 73.500 & 6.429 & 2.681 & 0.006 & 0.000 & 0.276 \\ 
      74 & 35.340 & 2.653 & 2.885 & 0.006 & 0.000 & 0.275 \\ 
      75 & 31.220 & 3.197 & 2.977 & 0.006 & 0.000 & 0.292 \\ 
      76 & 53.500 & 2.978 & 0.724 & 0.001 & 0.000 & 0.097 \\ 
      77 & 28.310 & 1.752 & 0.932 & 0.002 & 0.000 & 0.125 \\ 
      78 & 21.460 & 1.470 & 0.640 & 0.001 & 0.000 & 0.077 \\ 
      79 & 115.570 & 4.394 & 4.078 & 0.010 & 0.000 & 0.513 \\ 
      80 & 80.130 & 2.998 & 3.164 & 0.008 & 0.000 & 0.405 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #208.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-208-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #208
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-208-im
    #+RESULTS: cg-208-im
    [[file:/tmp/babel-1786g10/figure-1786brl.pdf]]

\clearpage
*** Component Type #209
    #+BEGIN_SRC R :results output latex 
      CG = 209
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:43 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    81 & 901.000 & 83.448 & 2.786 & 0.007 & 0.000 & 0.349 \\ 
      82 & 1204.000 & 74.125 & 0.841 & 0.002 & 0.000 & 0.233 \\ 
      83 & 1021.600 & 29.815 & 3.180 & 0.009 & 0.000 & 0.493 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #209.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-209-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #209
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-209-im
    #+RESULTS: cg-209-im
    [[file:/tmp/babel-1786g10/figure-1786nJB.pdf]]

\clearpage
*** Component Type #211
    #+BEGIN_SRC R :results output latex 
      CG = 211
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:43 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    61 & 2.098 & 0.281 & 0.901 & 0.002 & 0.000 & 0.079 \\ 
      62 & 0.550 & 0.139 & 0.667 & 0.001 & 0.000 & 0.038 \\ 
      63 & 0.600 & 0.059 & 0.665 & 0.001 & 0.000 & 0.046 \\ 
      64 & 0.371 & 0.041 & 0.649 & 0.001 & 0.000 & 0.043 \\ 
      65 & 0.607 & 0.048 & 0.147 & 0.001 & 0.000 & 0.033 \\ 
      66 & 0.474 & 0.039 & 0.849 & 0.003 & 0.000 & 0.105 \\ 
      67 & 0.243 & 0.039 & 0.142 & 0.001 & 0.000 & 0.026 \\ 
      68 & 1.054 & 0.078 & 1.085 & 0.002 & 0.000 & 0.076 \\ 
      69 & 0.745 & 0.052 & 0.804 & 0.002 & 0.000 & 0.061 \\ 
      70 & 0.270 & 0.020 & 0.097 & 0.001 & 0.000 & 0.024 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #211.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-211-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #211
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-211-im
    #+RESULTS: cg-211-im
    [[file:/tmp/babel-1786g10/figure-1786OoT.pdf]]

\clearpage
*** Component Type #214
    #+BEGIN_SRC R :results output latex 
      CG = 214
      print.cg.im.summary(CG)
    #+END_SRC

    #+RESULTS:
    #+BEGIN_EXPORT latex
    % latex table generated in R 3.2.2 by xtable 1.8-2 package
    % Mon Aug 29 14:09:44 2016
    \begin{table}[ht]
    \centering
    \begin{tabular}{rrrrrrr}
      \hline
     & mean.max & mean.avg & mean.pct & sd.max & sd.avg & sd.pct \\ 
      \hline
    106 & 58.300 & 2.148 & 0.112 & 0.001 & 0.000 & 0.101 \\ 
      107 & 138.300 & 13.429 & 0.386 & 0.005 & 0.000 & 0.397 \\ 
      108 & 33.800 & 2.973 & 0.565 & 0.003 & 0.000 & 0.188 \\ 
      109 & 17.390 & 1.265 & 0.579 & 0.003 & 0.000 & 0.193 \\ 
      110 & 15.860 & 1.504 & 0.580 & 0.003 & 0.000 & 0.219 \\ 
      111 & 16.900 & 1.404 & 0.129 & 0.001 & 0.000 & 0.123 \\ 
      112 & 9.740 & 0.912 & 0.159 & 0.002 & 0.000 & 0.142 \\ 
      113 & 14.500 & 0.714 & 0.129 & 0.082 & 0.001 & 6.788 \\ 
      114 & 46.500 & 1.743 & 0.713 & 0.007 & 0.000 & 0.528 \\ 
      115 & 29.570 & 1.182 & 0.529 & 0.006 & 0.000 & 0.406 \\ 
       \hline
    \end{tabular}
    \caption{Comparison of Component
			      Groups of type #214.} 
    \end{table}
    #+END_EXPORT

    #+NAME: cg-214-im
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
      plot_cg_im(CG)
    #+END_SRC

    #+CAPTION: Components of type #214
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:cg-214-im
    #+RESULTS: cg-214-im
    [[file:/tmp/babel-1786g10/figure-17861Gm.pdf]]

\clearpage
*** Loss-IM Relation
* Loss by Fate
** Loss by Fate (Lines)
    #+NAME: structloss.by.fate
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R :session *R-2*
      loss.by.fate <- read.csv("results/loss_by_fate", header=TRUE, sep="")
      fate.names = names(loss.by.fate)
      fate.im.name = fate.names[1]
      fate.names = fate.names[2:length(fate.names)]

      palette(rainbow(length(fate.names)))
      plot(NULL, xlim=range(loss.by.fate$IM),
           ylim=range(loss.by.fate$coll.mean),
   	 xlab="IM", ylab="Mean Loss",
   	 main="Mean Loss vs. IM")
      for (i in 1:length(fate.names)) {
          lines(loss.by.fate[,(i+1)] ~ loss.by.fate[,fate.im.name], col=i)
      }
      legend(x="topleft", ncol=1, legend=c(fate.names), fill=palette())
    #+END_SRC

    #+CAPTION: Mean Loss by FATE
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:structloss.by.fate
    #+RESULTS: structloss.by.fate
    [[file:/tmp/babel-1786g10/figure-1786BlB.pdf]]
   
** Loss by Fate (Solid)
    #+NAME: structloss.by.fate-filled
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R :session *R-2*
      loss.by.fate.summed <- read.csv("results/loss_by_fate", header=TRUE, sep="")
      names(loss.by.fate.summed) = c("IM", "Repair", "Demolition", "Collapse")
      fate.names = names(loss.by.fate.summed)
      fate.im.name = fate.names[1]
      fate.names = fate.names[2:length(fate.names)]

      loss.by.fate.summed$Demolition = loss.by.fate.summed$Demolition + loss.by.fate.summed$Repair
      loss.by.fate.summed$Collapse = loss.by.fate.summed$Collapse + loss.by.fate.summed$Demolition

      palette(rainbow(length(fate.names)))
      plot(NULL, xlim=range(loss.by.fate.summed$IM),
           ylim=range(loss.by.fate.summed$Collapse),
         xlab="IM", ylab="Mean Loss ($ Million)",
         main="Mean Loss vs. IM", yaxt="n")
      for (i in 1:length(fate.names)) {
          lines(loss.by.fate.summed[,(i+1)] ~ loss.by.fate.summed[,fate.im.name], col=i)
      }
      polygon(c(loss.by.fate.summed$IM, rev(loss.by.fate.summed$IM)),
              c(loss.by.fate.summed$Repair, 0 * loss.by.fate.summed$Repair),
              col=1)
      polygon(c(loss.by.fate.summed$IM, rev(loss.by.fate.summed$IM)),
              c(loss.by.fate.summed$Demolition, rev(loss.by.fate.summed$Repair)),
              col=2)
      polygon(c(loss.by.fate.summed$IM, rev(loss.by.fate.summed$IM)),
              c(loss.by.fate.summed$Collapse, rev(loss.by.fate.summed$Demolition)),
              col=3)
      legend(x="topleft", ncol=1, legend=c(fate.names), fill=palette())
      x=c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
      axis(2, at=x * 1E6, labels=x, las=2)
    #+END_SRC

    #+CAPTION: Mean Loss by FATE
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:structloss.by.fate-filled
    #+RESULTS: structloss.by.fate-filled
    [[file:/tmp/babel-1786g10/figure-1786oDU.pdf]]
   
** Loss Total, Normalised
    *I'm not sure these calculations are correct*
    #+NAME: structloss.by.fate-normalised
    #+HEADER: :results graphics
    #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R :session *R-2*
      loss.by.fate.normalised <- read.csv("results/loss_by_fate", header=TRUE, sep="")
      names(loss.by.fate.normalised) = c("IM", "Repair", "Demolition", "Collapse")
      fate.names = names(loss.by.fate.normalised)
      fate.im.name = fate.names[1]
      fate.names = fate.names[2:length(fate.names)]
      loss.by.fate.normalised$Total = loss.by.fate.normalised$Repair +
          loss.by.fate.normalised$Demolition + loss.by.fate.normalised$Collapse

      im.linear <- read.csv("results/im_rate_lin", header=TRUE, sep="")
      loss.by.fate.normalised$Scaled = loss.by.fate.normalised$Total * im.linear$lambda

      loss.by.fate.normalised$Normalised = loss.by.fate.normalised$Scaled / max(loss.by.fate.normalised$Scaled)

      plot(loss.by.fate.normalised$Normalised ~ loss.by.fate.normalised$IM, type="l",
          main="Normalised Loss", xlab="IM", ylab="Loss (normalised)")
    #+END_SRC

    #+CAPTION: Mean Loss by FATE
    #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
    #+NAME: fig:structloss.by.fate-normalised
    #+RESULTS: structloss.by.fate-normalised
    [[file:/tmp/babel-1786g10/figure-1786Pim.pdf]]
   
* Loss by EDP
   #+NAME: structloss.by.edp
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.edp <- read.csv("results/loss_by_edp", header=TRUE, sep="")
     edp.names = names(loss.by.edp)
     edp.im.name = edp.names[1]
     edp.names = edp.names[2:length(edp.names)]
     for (i in 2:length(edp.names)) {
         loss.by.edp[edp.names[i]] = loss.by.edp[edp.names[i]] + loss.by.edp[edp.names[i-1]]
     }
     palette(rainbow(length(edp.names)))
     plot(paleo.structloss.nc$mean.x ~ paleo.structloss.nc$IM)
     for (i in 1:length(edp.names)) {
         lines(loss.by.edp[,(i+1)] ~ loss.by.edp[,edp.im.name], col=i)
     }
     legend(x="topleft", ncol=2, legend=c(edp.names), fill=palette())
   #+END_SRC

   #+CAPTION: Mean Loss by EDP
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.edp
   #+RESULTS: structloss.by.edp
   [[file:/tmp/babel-1786g10/figure-1786bAC.pdf]]

   #+NAME: structloss.by.edp-20
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.edp <- read.csv("results/loss_by_edp", header=TRUE, sep="")
     edp.table = data.frame(c("Accel", "Drift"))

     for (i in seq(1:11)) {
              edp.table[1,i + 1] = loss.by.edp[20, 2 * (i - 1) + 1]
         if (i > 1) {
             edp.table[2, i + 1] = loss.by.edp[20, 2 * (i - 1) ]
         } else {
             edp.table[2, i + 1] = NA
         }
     }

     names(edp.table)=c("EDP", "Ground Floor", 
         "2nd Story", "3rd Story", "4th Story",
         "5th Story", "6th Story", "7th Story",
         "8th Story", "9th Story", "10th Story",
         "Roof")
      edp.table

      edp.data <- matrix(c(as.vector(edp.table[1,2:12], mode="numeric"),
   			as.vector(edp.table[2,2:12], mode="numeric")),
                         nrow=2, byrow=TRUE)
     barplot(edp.data, beside=TRUE, horiz=TRUE,
             names=names(edp.table[2:12]), legend=c("Accel", "Drift"),
             cex.names=0.7)
   #+END_SRC

   #+CAPTION: Mean Loss by EDP at IM=0.297
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.edp-20
   #+RESULTS: structloss.by.edp-20
   [[file:/tmp/babel-1786g10/figure-1786CfU.pdf]]

   #+NAME: structloss.by.edp-67
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.edp <- read.csv("results/loss_by_edp", header=TRUE, sep="")
     edp.table = data.frame(c("Accel", "Drift"))

     for (i in seq(1:11)) {
              edp.table[1,i + 1] = loss.by.edp[67, 2 * (i - 1) + 1]
         if (i > 1) {
             edp.table[2, i + 1] = loss.by.edp[67, 2 * (i - 1) ]
         } else {
             edp.table[2, i + 1] = NA
         }
     }

     names(edp.table)=c("EDP", "Ground Floor", 
         "2nd Story", "3rd Story", "4th Story",
         "5th Story", "6th Story", "7th Story",
         "8th Story", "9th Story", "10th Story",
         "Roof")
      edp.table

      edp.data <- matrix(c(as.vector(edp.table[1,2:12], mode="numeric"),
   			as.vector(edp.table[2,2:12], mode="numeric")),
                         nrow=2, byrow=TRUE)
     barplot(edp.data, beside=TRUE, horiz=TRUE,
             names=names(edp.table[2:12]), legend=c("Accel", "Drift"),
             cex.names=0.7)
   #+END_SRC

   #+CAPTION: Mean Loss by EDP at IM=1.0
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.edp-67
   #+RESULTS: structloss.by.edp-67
   [[file:/tmp/babel-1786g10/figure-1786p9m.pdf]]

* Loss by Component Type
   #+NAME: structloss.by.comp
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.comp <- read.csv("results/loss_by_frag", 
                              header=TRUE, sep="")
     comp.names = names(loss.by.comp)
     comp.im.name = comp.names[1]
     comp.names = comp.names[2:length(comp.names)]
     for (i in 2:length(comp.names)) {
         loss.by.comp[comp.names[i]] = 
             loss.by.comp[comp.names[i]] +
                 loss.by.comp[comp.names[i-1]]
     }
     palette(rainbow(length(comp.names)))
     ##plot(paleo.structloss.nc$mean.x ~ paleo.structloss.nc$IM)
     plot(NULL, xlim=range(paleo.structloss.nc$IM),
          ylim=range(paleo.structloss.nc$mean.x), 
          xlab="IM", ylab="Mean Loss ($ Million)",
          main="Mean Loss by Component Type", 
          yaxt="n")
     x=c(1, 2, 3, 4, 5, 6)
     axis(2, at=x * 1E6, labels=x, las=2)
     for (i in 1:length(comp.names)) {
         lines(loss.by.comp[,(i+1)] ~ loss.by.comp[,comp.im.name], col=i)
     }
     polygon(c(loss.by.comp[,comp.im.name],
               rev(loss.by.comp[,comp.im.name])),
             c(loss.by.comp[,2], 0 * loss.by.comp[,2]),
             col=1)
     for (i in 2:length(comp.names)) {
         polygon(c(loss.by.comp[,comp.im.name],
   		rev(loss.by.comp[,comp.im.name])),
             c(loss.by.comp[,(i + 1)], rev(loss.by.comp[,i])),
             col=i)
     }
   #+END_SRC

   #+CAPTION: Mean Loss by COMP
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.comp
   #+RESULTS: structloss.by.comp
   [[file:/tmp/babel-1786g10/figure-17861bC.pdf]]

   #+NAME: structloss.by.comp-20
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.comp <- read.csv("results/loss_by_frag", header=TRUE, sep="")
     palette(rainbow(length(comp.names)))
     pie(as.vector(loss.by.comp[20,2:length(comp.names)], mode="numeric"),
         label=lapply(comp.names, function(s) sprintf("#%s", strsplit(s, "\\.")[[1]][[2]])),
	 col=palette())
   #+END_SRC

   #+CAPTION: Mean Loss by Component Type at IM=0.297
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.comp-20
   #+RESULTS: structloss.by.comp-20
   [[file:/tmp/babel-1786g10/figure-1786c6U.pdf]]

   #+NAME: structloss.by.comp-67
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
     loss.by.comp <- read.csv("results/loss_by_frag", header=TRUE, sep="")
     palette(rainbow(length(comp.names)))
     pie(as.vector(loss.by.comp[67,2:length(comp.names)], mode="numeric"),
         label=lapply(comp.names, function(s) sprintf("#%s", strsplit(s, "\\.")[[1]][[2]])),
	 col=palette())
   #+END_SRC

   #+CAPTION: Mean Loss by Component Type at IM=1.0
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.by.comp-67
   #+RESULTS: structloss.by.comp-67
   [[file:/tmp/babel-1786g10/figure-1786DZn.pdf]]
   
* Annual Loss
  The annual loss for the entire structure
  #+BEGIN_SRC R  :results value 
    paleo.ann.loss <- scan(paste(results.dir, "ann_loss", 
                             sep=""), skip=3)
    neo.ann.loss <- as.numeric(scan("results/ann_loss",
                                    skip=1))

    paste(
        sprintf("%20s|%15s|%15s|%15s", 
                "", "Paleo", "Neo", "Error(%)"),
        sprintf("%20s|%15.3e|%15.3e|%15.3f|", "E(loss)", 
                paleo.ann.loss[1],
                neo.ann.loss[1], 
                (100*abs(neo.ann.loss[1] - 
                             paleo.ann.loss[1]) / 
                                 paleo.ann.loss[1])),
        sprintf("%20s|%15.3e|%15.3e|%15.3f|", 
                "SD(ln(loss))", 
                paleo.ann.loss[2],
                neo.ann.loss[2], 
                (100*abs(neo.ann.loss[2] - 
                             paleo.ann.loss[2]) /
                                 paleo.ann.loss[2])),
        sep="\n")
  #+END_SRC
  
  #+RESULTS:
  |              |     Paleo |       Neo | Error(%) |
  | E(loss)      | 1.175e+04 | 1.035e+04 |   11.859 |
  | SD(ln(loss)) | 2.491e+00 | 2.441e+00 |     1.99 |

  
* Scratch 							   :noexport:
   :PROPERTIES:
   :header-args: :eval no-export
   :END:
#+PROPERTY: header-args    

   Code to check sample points are the same
   EDP-IM relationships:
   #+BEGIN_SRC sh :results output
   for i in $(seq 21); do    
      f=example1a_im_edp_${i}.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/edp-im-${i}
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
   1.0000E-02 ;  2.500 ;  199
#+end_example

   EDP-rate relationships
   #+BEGIN_SRC sh :results output
   for i in $(seq 21); do    
      f=example1a_edp_${i}_rate.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/edp-${i}-rate.txt
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   1.0000E-03 ;  0.1500 ;  149
   1.0000E-03 ;  0.1000 ;  149
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
   1.0000E-03 ;  0.1000 ;  199
   5.0000E-02 ;  5.000 ;  199
#+end_example

   Loss-edp
   #+BEGIN_SRC sh :results output
   for i in $(seq 115); do    
      f=example1a_loss_${i}_edp.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/pg-${i}-edp
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $i":" $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
      echo $i":" \
           $(guile -c "(display (- $min_n $min_p))") \
           $(guile -c "(display (- $max_n $max_p))") \
           $(guile -c "(display (- $count_n $count_p))")

   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   1: 1.0000E-03 ;  0.1000 ;  149
   1: -0.001 -0.1 -149
   2: 1.0000E-03 ;  0.1000 ;  149
   2: -0.001 -0.1 -149
   3: 1.0000E-03 ;  0.1000 ;  199
   3: -0.001 -0.1 -199
   4: 1.0000E-03 ;  0.1000 ;  199
   4: -0.001 -0.1 -199
   5: 1.0000E-03 ;  0.1000 ;  199
   5: -0.001 -0.1 -199
   6: 1.0000E-03 ;  0.1000 ;  199
   6: -0.001 -0.1 -199
   7: 1.0000E-03 ;  0.1000 ;  199
   7: -0.001 -0.1 -199
   8: 1.0000E-03 ;  0.1000 ;  199
   8: -0.001 -0.1 -199
   9: 1.0000E-03 ;  0.1000 ;  199
   9: -0.001 -0.1 -199
   10: 1.0000E-03 ;  0.1000 ;  199
   10: -0.001 -0.1 -199
   11: 1.0000E-03 ;  0.1000 ;  199
   11: -0.001 -0.1 -199
   12: 1.0000E-03 ;  0.1000 ;  199
   12: -0.001 -0.1 -199
   13: 1.0000E-03 ;  0.1000 ;  199
   13: -0.001 -0.1 -199
   14: 1.0000E-03 ;  0.1000 ;  199
   14: -0.001 -0.1 -199
   15: 1.0000E-03 ;  0.1000 ;  199
   15: -0.001 -0.1 -199
   16: 1.0000E-03 ;  0.1000 ;  199
   16: -0.001 -0.1 -199
   17: 1.0000E-03 ;  0.1000 ;  199
   17: -0.001 -0.1 -199
   18: 1.0000E-03 ;  0.1000 ;  199
   18: -0.001 -0.1 -199
   19: 1.0000E-03 ;  0.1000 ;  199
   19: -0.001 -0.1 -199
   20: 1.0000E-03 ;  0.1000 ;  199
   20: -0.001 -0.1 -199
   21: 1.0000E-03 ;  0.1000 ;  149
   21: -0.001 -0.1 -149
   22: 1.0000E-03 ;  0.1000 ;  199
   22: -0.001 -0.1 -199
   23: 1.0000E-03 ;  0.1000 ;  199
   23: -0.001 -0.1 -199
   24: 1.0000E-03 ;  0.1000 ;  199
   24: -0.001 -0.1 -199
   25: 1.0000E-03 ;  0.1000 ;  199
   25: -0.001 -0.1 -199
   26: 1.0000E-03 ;  0.1000 ;  199
   26: -0.001 -0.1 -199
   27: 1.0000E-03 ;  0.1000 ;  199
   27: -0.001 -0.1 -199
   28: 1.0000E-03 ;  0.1000 ;  199
   28: -0.001 -0.1 -199
   29: 1.0000E-03 ;  0.1000 ;  199
   29: -0.001 -0.1 -199
   30: 1.0000E-03 ;  0.1000 ;  199
   30: -0.001 -0.1 -199
   31: 1.0000E-03 ;  0.1000 ;  149
   31: -0.001 -0.1 -149
   32: 1.0000E-03 ;  0.1000 ;  199
   32: -0.001 -0.1 -199
   33: 1.0000E-03 ;  0.1000 ;  199
   33: -0.001 -0.1 -199
   34: 1.0000E-03 ;  0.1000 ;  199
   34: -0.001 -0.1 -199
   35: 1.0000E-03 ;  0.1000 ;  199
   35: -0.001 -0.1 -199
   36: 1.0000E-03 ;  0.1000 ;  199
   36: -0.001 -0.1 -199
   37: 1.0000E-03 ;  0.1000 ;  199
   37: -0.001 -0.1 -199
   38: 1.0000E-03 ;  0.1000 ;  199
   38: -0.001 -0.1 -199
   39: 1.0000E-03 ;  0.1000 ;  199
   39: -0.001 -0.1 -199
   40: 1.0000E-03 ;  0.1000 ;  199
   40: -0.001 -0.1 -199
   41: 1.0000E-03 ;  0.1000 ;  149
   41: -0.001 -0.1 -149
   42: 1.0000E-03 ;  0.1000 ;  199
   42: -0.001 -0.1 -199
   43: 1.0000E-03 ;  0.1000 ;  199
   43: -0.001 -0.1 -199
   44: 1.0000E-03 ;  0.1000 ;  199
   44: -0.001 -0.1 -199
   45: 1.0000E-03 ;  0.1000 ;  199
   45: -0.001 -0.1 -199
   46: 1.0000E-03 ;  0.1000 ;  199
   46: -0.001 -0.1 -199
   47: 1.0000E-03 ;  0.1000 ;  199
   47: -0.001 -0.1 -199
   48: 1.0000E-03 ;  0.1000 ;  199
   48: -0.001 -0.1 -199
   49: 1.0000E-03 ;  0.1000 ;  199
   49: -0.001 -0.1 -199
   50: 1.0000E-03 ;  0.1000 ;  199
   50: -0.001 -0.1 -199
   51: 5.0000E-02 ;  5.000 ;  199
   51: -0.05 -5.0 -199
   52: 5.0000E-02 ;  5.000 ;  199
   52: -0.05 -5.0 -199
   53: 5.0000E-02 ;  5.000 ;  199
   53: -0.05 -5.0 -199
   54: 5.0000E-02 ;  5.000 ;  199
   54: -0.05 -5.0 -199
   55: 5.0000E-02 ;  5.000 ;  199
   55: -0.05 -5.0 -199
   56: 5.0000E-02 ;  5.000 ;  199
   56: -0.05 -5.0 -199
   57: 5.0000E-02 ;  5.000 ;  199
   57: -0.05 -5.0 -199
   58: 5.0000E-02 ;  5.000 ;  199
   58: -0.05 -5.0 -199
   59: 5.0000E-02 ;  5.000 ;  199
   59: -0.05 -5.0 -199
   60: 5.0000E-02 ;  5.000 ;  199
   60: -0.05 -5.0 -199
   61: 5.0000E-02 ;  5.000 ;  199
   61: -0.05 -5.0 -199
   62: 5.0000E-02 ;  5.000 ;  199
   62: -0.05 -5.0 -199
   63: 5.0000E-02 ;  5.000 ;  199
   63: -0.05 -5.0 -199
   64: 5.0000E-02 ;  5.000 ;  199
   64: -0.05 -5.0 -199
   65: 5.0000E-02 ;  5.000 ;  199
   65: -0.05 -5.0 -199
   66: 5.0000E-02 ;  5.000 ;  199
   66: -0.05 -5.0 -199
   67: 5.0000E-02 ;  5.000 ;  199
   67: -0.05 -5.0 -199
   68: 5.0000E-02 ;  5.000 ;  199
   68: -0.05 -5.0 -199
   69: 5.0000E-02 ;  5.000 ;  199
   69: -0.05 -5.0 -199
   70: 5.0000E-02 ;  5.000 ;  199
   70: -0.05 -5.0 -199
   71: 1.0000E-03 ;  0.1500 ;  149
   71: -0.001 -0.15 -149
   72: 5.0000E-02 ;  5.000 ;  199
   72: -0.05 -5.0 -199
   73: 5.0000E-02 ;  5.000 ;  199
   73: -0.05 -5.0 -199
   74: 5.0000E-02 ;  5.000 ;  199
   74: -0.05 -5.0 -199
   75: 5.0000E-02 ;  5.000 ;  199
   75: -0.05 -5.0 -199
   76: 5.0000E-02 ;  5.000 ;  199
   76: -0.05 -5.0 -199
   77: 5.0000E-02 ;  5.000 ;  199
   77: -0.05 -5.0 -199
   78: 5.0000E-02 ;  5.000 ;  199
   78: -0.05 -5.0 -199
   79: 5.0000E-02 ;  5.000 ;  199
   79: -0.05 -5.0 -199
   80: 5.0000E-02 ;  5.000 ;  199
   80: -0.05 -5.0 -199
   81: 5.0000E-02 ;  5.000 ;  199
   81: -0.05 -5.0 -199
   82: 5.0000E-02 ;  5.000 ;  199
   82: -0.05 -5.0 -199
   83: 5.0000E-02 ;  5.000 ;  199
   83: -0.05 -5.0 -199
   84: 5.0000E-02 ;  5.000 ;  199
   84: -0.05 -5.0 -199
   85: 1.0000E-03 ;  0.1500 ;  149
   85: -0.001 -0.15 -149
   86: 1.0000E-03 ;  0.1000 ;  149
   86: -0.001 -0.1 -149
   87: 1.0000E-03 ;  0.1000 ;  199
   87: -0.001 -0.1 -199
   88: 1.0000E-03 ;  0.1000 ;  199
   88: -0.001 -0.1 -199
   89: 1.0000E-03 ;  0.1000 ;  199
   89: -0.001 -0.1 -199
   90: 1.0000E-03 ;  0.1000 ;  199
   90: -0.001 -0.1 -199
   91: 1.0000E-03 ;  0.1000 ;  199
   91: -0.001 -0.1 -199
   92: 1.0000E-03 ;  0.1000 ;  199
   92: -0.001 -0.1 -199
   93: 1.0000E-03 ;  0.1000 ;  199
   93: -0.001 -0.1 -199
   94: 1.0000E-03 ;  0.1000 ;  199
   94: -0.001 -0.1 -199
   95: 1.0000E-03 ;  0.1000 ;  199
   95: -0.001 -0.1 -199
   96: 1.0000E-03 ;  0.1000 ;  149
   96: -0.001 -0.1 -149
   97: 1.0000E-03 ;  0.1000 ;  199
   97: -0.001 -0.1 -199
   98: 1.0000E-03 ;  0.1000 ;  199
   98: -0.001 -0.1 -199
   99: 1.0000E-03 ;  0.1000 ;  199
   99: -0.001 -0.1 -199
   100: 1.0000E-03 ;  0.1000 ;  199
   100: -0.001 -0.1 -199
   101: 1.0000E-03 ;  0.1000 ;  199
   101: -0.001 -0.1 -199
   102: 1.0000E-03 ;  0.1000 ;  199
   102: -0.001 -0.1 -199
   103: 1.0000E-03 ;  0.1000 ;  199
   103: -0.001 -0.1 -199
   104: 1.0000E-03 ;  0.1000 ;  199
   104: -0.001 -0.1 -199
   105: 1.0000E-03 ;  0.1000 ;  199
   105: -0.001 -0.1 -199
   106: 1.0000E-03 ;  0.1500 ;  149
   106: -0.001 -0.15 -149
   107: 5.0000E-02 ;  5.000 ;  199
   107: -0.05 -5.0 -199
   108: 5.0000E-02 ;  5.000 ;  199
   108: -0.05 -5.0 -199
   109: 5.0000E-02 ;  5.000 ;  199
   109: -0.05 -5.0 -199
   110: 5.0000E-02 ;  5.000 ;  199
   110: -0.05 -5.0 -199
   111: 5.0000E-02 ;  5.000 ;  199
   111: -0.05 -5.0 -199
   112: 5.0000E-02 ;  5.000 ;  199
   112: -0.05 -5.0 -199
   113: 5.0000E-02 ;  5.000 ;  199
   113: -0.05 -5.0 -199
   114: 5.0000E-02 ;  5.000 ;  199
   114: -0.05 -5.0 -199
   115: 5.0000E-02 ;  5.000 ;  199
   115: -0.05 -5.0 -199
#+end_example

   Loss-im
   #+BEGIN_SRC sh :results output
   for i in $(seq 115); do    
      f=example1a_loss_${i}_im.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/pg-${i}-im
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      #echo  $min_n  $min_p "; " $max_n - $max_p "; " $count_n - $count_p
      echo $(guile -c "(display (- $min_n $min_p))") \
           $(guile -c "(display (- $max_n $max_p))") \
           $(guile -c "(display (- $count_n $count_p))")
   done
   
   #+END_SRC

   #+RESULTS:
   #+begin_example
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
   -0.01 -2.5 -199
#+end_example

*** Per-unit cost
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
    #+BEGIN_SRC R
     per.unit.cost <- function(low.count, price.at.low, 
                               high.count, price.at.high,
                               n)
     {
         if (n <= low.count) {
             unit.price <- price.at.low
         } else if (n >= high.count) {
             unit.price <- price.at.high
         } else {
             ratio = (n - low.count)/(high.count - low.count)
             #total.price.low <- price.at.low * low.count
             #total.price.high <- price.at.high * high.count

             #total.price.n <- total.price.low + ratio * (total.price.high - total.price.low)
             #unit.price <- total.price.n / n
	     unit.price <- price.at.low + ratio * (price.at.high - price.at.low)
         }

         return(unit.price)
     }

     cost <- function(count) {
         sapply(count, function(n) {
             low.count <- 9
             high.count <- 900
             price.at.low <- 58.4
             price.at.high <- 43.2

             return(n * per.unit.cost(low.count, price.at.low, 
                                      high.count, price.at.high,
                                      n))
         })}

     plot(cost, from=0, to = 1000)
    #+END_SRC

    #+RESULTS:
    [[file:/tmp/babel-1786g10/figure-1786qFi.pdf]]


    #+BEGIN_SRC R :results output
      print("203--693 units")
      print(per.unit.cost(9,  58.4, 900,  43.2, 693))
      print(per.unit.cost(9, 297.9, 900, 277.8, 693))
      print("")
      print("204--2 units")
      print(per.unit.cost(3, 56000, 5, 33600, 2))
      print("")
      print("205--4 units")
      print(per.unit.cost(2, 220000, 8, 150000, 4))
      print("")
      print("208--53 units")
      print(per.unit.cost(10, 2500, 100, 1000, 53))
      print("")
      print("209--16 units")
      print(per.unit.cost(2, 50000, 6, 40000, 16))
    #+END_SRC

    #+RESULTS:
    #+begin_example
    [1] "203--693 units"
    [1] 46.73131
    [1] 282.4697
    [1] ""
    [1] "204--2 units"
    [1] 56000
    [1] ""
    [1] "205--4 units"
    [1] 196666.7
    [1] ""
    [1] "208--53 units"
    [1] 1783.333
    [1] ""
    [1] "209--16 units"
    [1] 40000
#+end_example

* DS-IM
   #+HEADER: :results output
   #+BEGIN_SRC R :session *R-2*
     graph.ds <- function(n) {
         edp.values = levels(factor(cgs.descrip$EDP))
         edp = edp.values[n]
         cgs = cgs.descrip[cgs.descrip$EDP==edp,]
         palette(rainbow(length(cgs$Type)))
         plot(NULL, xlim=c(0,3), ylim=c(0,1), main="", xlab="IM", ylab="p")
    
         for (i in 1:length(cgs$Index)) {
             cg = cgs$Index[i]
             ds.im <- read.csv(
                 sprintf("c-results/ds_im_%d.txt", cg), header=TRUE, sep="")
             N = length(names(ds.im)) - 1
             for (j in 1:N) {
                 points(ds.im[,(j+1)] ~ ds.im$IM.1, col=i, pch=j);
             }
         }
     }
   #+END_SRC

   #+RESULTS:

   #+NAME: p.ds.im-1
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(1)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #1
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-1
   #+RESULTS: p.ds.im-1
   [[file:/tmp/babel-1786g10/figure-1786sjA.pdf]]

   #+NAME: p.ds.im-2
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(2)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #2
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-2
   #+RESULTS: p.ds.im-2
   [[file:/tmp/babel-1786g10/figure-1786dCQ.pdf]]

   #+NAME: p.ds.im-3
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(3)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #3
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-3
   #+RESULTS: p.ds.im-3
   [[file:/tmp/babel-1786g10/figure-1786Ehi.pdf]]

   #+NAME: p.ds.im-4
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(4)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #4
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-4
   #+RESULTS: p.ds.im-4
   [[file:/tmp/babel-1786g10/figure-1786r_0.pdf]]

   #+NAME: p.ds.im-5
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(5)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #5
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-5
   #+RESULTS: p.ds.im-5
   [[file:/tmp/babel-1786g10/figure-17863dQ.pdf]]

   #+NAME: p.ds.im-6
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(6)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #6
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-6
   #+RESULTS: p.ds.im-6
   [[file:/tmp/babel-1786g10/figure-1786e8i.pdf]]

   #+NAME: p.ds.im-7
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(7)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #7
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-7
   #+RESULTS: p.ds.im-7
   [[file:/tmp/babel-1786g10/figure-1786Fb1.pdf]]

   #+NAME: p.ds.im-8
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(8)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #8
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-8
   #+RESULTS: p.ds.im-8
   [[file:/tmp/babel-1786g10/figure-1786R5Q.pdf]]

   #+NAME: p.ds.im-9
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(9)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #9
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-9
   #+RESULTS: p.ds.im-9
   [[file:/tmp/babel-1786g10/figure-17864Xj.pdf]]

   #+NAME: p.ds.im-10
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(10)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #10
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-10
   #+RESULTS: p.ds.im-10
   [[file:/tmp/babel-1786g10/figure-1786f21.pdf]]

   #+NAME: p.ds.im-11
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(11)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #11
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-11
   #+RESULTS: p.ds.im-11
   [[file:/tmp/babel-1786g10/figure-1786rUR.pdf]]

   #+NAME: p.ds.im-12
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(12)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #12
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-12
   #+RESULTS: p.ds.im-12
   [[file:/tmp/babel-1786g10/figure-1786Szj.pdf]]

   #+NAME: p.ds.im-13
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(13)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #13
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-13
   #+RESULTS: p.ds.im-13
   [[file:/tmp/babel-1786g10/figure-17865R2.pdf]]

   #+NAME: p.ds.im-14
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(14)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #14
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-14
   #+RESULTS: p.ds.im-14
   [[file:/tmp/babel-1786g10/figure-1786FwR.pdf]]

   #+NAME: p.ds.im-15
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(15)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #15
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-15
   #+RESULTS: p.ds.im-15
   [[file:/tmp/babel-1786g10/figure-1786sOk.pdf]]

   #+NAME: p.ds.im-16
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(16)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #16
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-16
   #+RESULTS: p.ds.im-16
   [[file:/tmp/babel-1786g10/figure-1786Tt2.pdf]]

   #+NAME: p.ds.im-17
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(17)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #17
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-17
   #+RESULTS: p.ds.im-17
   [[file:/tmp/babel-1786g10/figure-1786fLS.pdf]]

   #+NAME: p.ds.im-18
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(18)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #18
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-18
   #+RESULTS: p.ds.im-18
   [[file:/tmp/babel-1786g10/figure-1786Gqk.pdf]]

   #+NAME: p.ds.im-19
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(19)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #19
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-19
   #+RESULTS: p.ds.im-19
   [[file:/tmp/babel-1786g10/figure-1786SIA.pdf]]

   #+NAME: p.ds.im-20
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(20)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #20
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-20
   #+RESULTS: p.ds.im-20
   [[file:/tmp/babel-1786g10/figure-17865mS.pdf]]

   #+NAME: p.ds.im-21
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R :session *R-2*
   graph.ds(21)
   #+END_SRC

   #+CAPTION: Probability of Damage States for EDP #21
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:p.ds.im-21
   #+RESULTS: p.ds.im-21
   [[file:/tmp/babel-1786g10/figure-1786gFl.pdf]]
