#+Title:     SLAT: Example 1 with Collapse Added
#+AUTHOR:    Michael Gauland
#+EMAIL:     michael.gauland@canterbury.ac.nz
#+DATE:      {{{time(%Y-%m-%d %H:%M)}}}
#+DESCRIPTION: 
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:6 num:t toc:4 \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:dvipng LaTeX:dvipng skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   timestamp:t email:t
#+OPTIONS:   ':t
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{unicode-math}
#+LaTex_header: \usepackage{epstopdf}
#+LATEX_HEADER: \usepackage{register}
#+LATEX_HEADER: \usepackage{bytefield}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabulary}
#+LATEX_HEADER: \usepackage[section]{placeins}
#+LATEX_HEADER: \usepackage[htt]{hyphenat}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \lstset{keywordstyle=\color{blue}\bfseries}
#+LATEX_HEADER: \newfontfamily\listingsfont[Scale=.7]{DejaVu Sans Mono}
#+LATEX_HEADER: \lstset{basicstyle=\listingsfont}
#+LATEX_HEADER: \lstset{showspaces=false}
#+LATEX_HEADER: \lstset{columns=fixed}
#+LATEX_HEADER: \lstset{extendedchars=true}
#+LATEX_HEADER: \lstset{frame=shadowbox}
#+LATEX_HEADER: \lstset{basicstyle=\ttfamily}
#+LATEX_HEADER: \definecolor{mygray}{gray}{0.8}
#+LATEX_HEADER: \lstset{rulesepcolor=\color{mygray}}
#+LATEX_HEADER: \lstdefinelanguage{dash}{rulecolor=\color{green},rulesepcolor=\color{mygray},frameround=ffff,backgroundcolor=\color{white}}
#+LATEX_HEADER: \lstdefinelanguage{fundamental}{basicstyle=\ttfamily\scriptsize,rulesepcolor=\color{cyan},frameround=tttt,backgroundcolor=\color{white},breaklines=true}
#+LATEX_HEADER: \usepackage{pst-circ}
#+LATEX_HEADER: \usepackage[hang,small,bf]{caption}
#+LATEX_HEADER: \setlength{\captionmargin}{20pt}
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+STARTUP: overview
#+STARTUP: align
#+STARTUP: noinlineimages
#+PROPERTY: header-args:R  :session *R-1*
#+PROPERTY: header-args    :exports results

\clearpage
* Initialisation
  The code in this section reads in the input data, as well as the results
  produces by the old ("paleo") and new ("neo") versions of SLAT.

  Set up variables to make it easier to get to the files:
  #+BEGIN_SRC R  :results output
    paleo.dir = paste("~/SLATv1.15_Public/",
	"example1a_collapse/", sep="")
    results.dir = paste(paleo.dir, "results/", sep="")

    paleo2.dir = paste("~/SLATv1.15_Public/",
	"example2_10storeybuilding/", sep="")
    results2.dir = paste(paleo2.dir, "results/", sep="")
  #+END_SRC

  #+RESULTS:
  
\clearpage
* IM
  Read the IM rate data:
  #+BEGIN_SRC R  :results output
    ## Read in the IM data:
    paleo.im <- read.csv(
        paste(results.dir, "im-rate.txt", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.im) = c("IM", "lambda")


    paleo2.im <- read.csv(
        paste(results2.dir, "im-rate", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.im) = c("IM", "lambda")

    neo.im <- read.csv("example1a_im_rate", 
                       header=TRUE, sep="")

    input.im <- read.csv(
        paste(paleo.dir, "IMrateSa15data.txt", sep=""),
        skip=2, header=FALSE, sep="")
    names(input.im) = c("IM", "lambda")
  #+END_SRC
  
  #+RESULTS:

  Plot it (Figure [[fig:im-rate]]):
  #+NAME: im-rate
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R
     palette(c("red", "blue", "green", "cyan"))
     plot(paleo.im$lambda ~ paleo.im$IM, log="xy", 
  	xlab="IM", ylab="lambda", main="IM Rate",
  	type="l", lwd=5, col=1,
  	xlim=c(0.01, 3.0), ylim=c(1E-8, 1E0),
  	pch=25)

    lines(neo.im$lambda ~ neo.im$IM, lwd=3, col=2, pch=24)

    points(input.im$lambda ~ input.im$IM, col=3)

    lines(paleo2.im$lambda ~ paleo2.im$IM, col=4, lwd=1)

    legend(x="topright",
  	 legend=c("Paleo", "Neo", "Input", "Paleo2"),
  	 fill=palette())
  #+END_SRC

  #+CAPTION: IM rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:im-rate
  #+RESULTS: im-rate
  [[file:/tmp/babel-1752Epe/figure-1752IwU.pdf]]

  Compare the two versions (assumes same IM values are used):
  #+BEGIN_SRC R
    sprintf("Max difference in IM rate is %3.2f%%",
        100 * max(abs(paleo.im$lambda - neo.im$lambda)
  		/ paleo.im$lambda))
  #+END_SRC

  #+RESULTS:
  : Max difference is 100.00%

\clearpage
* EDP #1
** EDP IM
   Read the EDP #1 IM data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp1.im <- read.csv(
         paste(results.dir, "edp-im-1", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp1.im) = c("IM", "mean_x", "sd_ln_x")

     neo.edp1.im <- read.csv("example1a_im_edp_1.txt",
         header=TRUE, sep="")
   #+END_SRC

   #+RESULTS:

   Compare the mean and standard deviation (in log space) of the EDP #1-IM
   relationship:
   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(mean error) is %3.2f%%.", 
                 100 * max(abs(neo.edp1.im$mean_x - 
  				 paleo.edp1.im$mean_x)
  			 / paleo.edp1.im$mean_x)),
         sprintf("Mean (mean error) is %3.2f%%.", 
                 100 * mean((neo.edp1.im$mean_x - 
                                 paleo.edp1.im$mean_x)
  			  / paleo.edp1.im$mean_x)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(sd_ln_x error) is %3.2f%%.", 
                 100 * max(abs(neo.edp1.im$sd_ln_x - 
    			       paleo.edp1.im$sd_ln_x)
    		       / paleo.edp1.im$sd_ln_x)),
         sprintf("Mean sd_ln_x error is %3.2f%%.", 
                 100 * mean((neo.edp1.im$sd_ln_x - 
    			       paleo.edp1.im$sd_ln_x)
    		       / paleo.edp1.im$sd_ln_x)),
         sep="\n")
   #+END_SRC

   Plot the mean (Figure [[fig:edp-1-im-mean]] and [[fig:edp-1-im-mean-zoom]]) and
   standard deviation (Figure [[fig:edp-1-im-sd-ln]]):
   #+NAME: edp-1-im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
       palette(c("red", "blue"))
       plot(paleo.edp1.im$mean_x ~ paleo.edp1.im$IM, log="", 
  	  xlab="IM", ylab="EDP", main="mean(EDP 1)-IM",
	  lwd=5,
  	  type="p", col=1)

       lines(neo.edp1.im$mean_x ~ neo.edp1.im$IM, col=2, lwd=3)

       legend(x="right", legend=c("Paleo", "Neo"),
  	  fill=palette())
   #+END_SRC

   #+RESULTS:

   #+CAPTION: mean(EDP #1) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-1-im-mean
   #+RESULTS: edp-1-im-mean
   [[file:/tmp/babel-1752Epe/figure-1752I_a.pdf]]

   #+NAME: edp-1-im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
     palette(c("red", "blue"))
     plot(paleo.edp1.im$mean_x ~ paleo.edp1.im$IM, log="", 
          xlab="IM", ylab="EDP", main="mean(EDP 1)-IM",
          lwd=5,
          xlim=c(0.8, 1.2),
          type="p", col=1)

     lines(neo.edp1.im$mean_x ~ neo.edp1.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+Caption: mean(EDP #1) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-1-im-mean-zoom
   #+RESULTS: edp-1-im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752W0t.pdf]]

   #+NAME: edp-1-im-sd-ln
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp1.im$sd_ln_x ~ paleo.edp1.im$IM, log="", 
          xlab="IM", ylab="EDP", main="sd(ln(EDP 1))-IM",
          lwd=5,
          type="p", col=1)

     lines(neo.edp1.im$sd_ln_x ~ neo.edp1.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: sd(ln(EDP #1)) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-1-im-sd-ln
   #+RESULTS: edp-1-im-sd-ln
   [[file:/tmp/babel-1752Epe/figure-1752IPK.pdf]]

** EDP Rate
   Read the EDP #1 rate data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp1.rate <- read.csv(
         paste(results.dir, "edp-1-rate.txt", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp1.rate) = c("EDP", "lambda")

     neo.edp1.rate <- read.csv("example1a_edp_1_rate.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the mean and standard deviation:
   #+BEGIN_SRC R   :results value 
     diff <- (paleo.edp1.rate$lambda
                  - neo.edp1.rate$lambda)
     diff.pct <- diff / paleo.edp1.rate$lambda
     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct))),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff), 
                 100 * mean(diff.pct)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 9.499000e-03 (8.23%). |
   | Mean error is 1.757726e-03 (0.58%).     |

   Plot it (Figure [[fig:edp-1-rate]]):
   #+NAME: edp-1-rate
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp1.rate$lambda ~ paleo.edp1.rate$EDP, log="xy", 
          xlab="EDP", ylab="lambda", main="EDP #1 Rate",
          lwd=5,
          type="p", col=1)

     lines(neo.edp1.rate$lambda ~ neo.edp1.rate$EDP, col=2,
         lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: EDP #1 rate calculations
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-1-rate
   #+RESULTS: edp-1-rate
   [[file:/tmp/babel-1752Epe/figure-1752vjD.pdf]]

\clearpage
* EDP #2
** EDP IM
   Read the EDP #2 IM data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp2.im <- read.csv(
         paste(results.dir, "edp-im-2", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp2.im) = c("IM", "mean_x", "sd_ln_x")

     neo.edp2.im <- read.csv("example1a_im_edp_2.txt",
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the mean and standard deviation:
   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(mean error) is %3.2f%%.", 
                 100 * max(abs(neo.edp2.im$mean_x - 
  				 paleo.edp2.im$mean_x)
  			 / paleo.edp2.im$mean_x)),
         sprintf("Mean (mean error) is %3.2f%%.", 
                 100 * mean((neo.edp2.im$mean_x - 
                                 paleo.edp2.im$mean_x)
  			  / paleo.edp2.im$mean_x)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(sd_ln_x error) is %3.2f%%.", 
                 100 * max(abs(neo.edp2.im$sd_ln_x - 
    			       paleo.edp2.im$sd_ln_x)
    		       / paleo.edp2.im$sd_ln_x)),
         sprintf("Mean sd_ln_x error is %3.2f%%.", 
                 100 * mean((neo.edp2.im$sd_ln_x - 
    			       paleo.edp2.im$sd_ln_x)
    		       / paleo.edp2.im$sd_ln_x)),
         sep="\n")
   #+END_SRC

   Plot the mean (Figure [[fig:edp-2-im-mean]] and [[fig:edp-2-im-mean-zoom]]) and
   standard deviation (Figure [[fig:edp-2-im-sd-ln]]):d
   #+NAME: edp-2-im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
       palette(c("red", "blue"))
       plot(paleo.edp2.im$mean_x ~ paleo.edp2.im$IM, log="", 
  	  xlab="IM", ylab="EDP", main="mean(EDP 2)-IM",
	  lwd=5,
  	  type="p", col=1)

       lines(neo.edp2.im$mean_x ~ neo.edp2.im$IM, col=2, lwd=3)

       legend(x="right", legend=c("Paleo", "Neo"),
  	  fill=palette())
   #+END_SRC

   #+RESULTS:

   #+CAPTION: men(EDP #2) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-2-im-mean
   #+RESULTS: edp-2-im-mean
   [[file:/tmp/babel-1752Epe/figure-1752vVb.pdf]]

   #+NAME: edp-2-im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
     palette(c("red", "blue"))
     plot(paleo.edp2.im$mean_x ~ paleo.edp2.im$IM, log="", 
          xlab="IM", ylab="EDP", main="mean(EDP 2)-IM",
          lwd=5,
          xlim=c(0.8, 1.2),
          type="p", col=1)

     lines(neo.edp2.im$mean_x ~ neo.edp2.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+Caption: men(EDP #2) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-2-im-mean-zoom
   #+RESULTS: edp-2-im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752W0t.pdf]]

   #+NAME: edp-2-im-sd-ln
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp2.im$sd_ln_x ~ paleo.edp2.im$IM, log="", 
          xlab="IM", ylab="EDP", main="sd(ln(EDP 2))-IM",
          lwd=5,
          type="p", col=1)

     lines(neo.edp2.im$sd_ln_x ~ neo.edp2.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: sd(ln(EDP #2)) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-2-im-sd-ln
   #+RESULTS: edp-2-im-sd-ln
   [[file:/tmp/babel-1752Epe/figure-1752SrH.pdf]]

** EDP Rate
   Read the EDP #2 rate data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp2.rate <- read.csv(
         paste(results.dir, "edp-2-rate.txt", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp2.rate) = c("EDP", "lambda")

     neo.edp2.rate <- read.csv("example1a_edp_2_rate.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   Compare the mean and standard deviation:
   #+BEGIN_SRC R   :results value 
     diff <- (paleo.edp2.rate$lambda
                  - neo.edp2.rate$lambda)
     diff.pct <- diff / paleo.edp2.rate$lambda
     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct))),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff), 
                 100 * mean(diff.pct)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 9.499000e-03 (8.23%). |
   | Mean error is 1.757726e-03 (0.58%).     |

   Plot the rate (Figure [[fig:edp-2-rate]]):
   #+NAME: edp-2-rate
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp2.rate$lambda ~ paleo.edp2.rate$EDP, log="xy", 
          xlab="EDP", ylab="lambda", main="EDP #2 Rate",
          lwd=5,
          type="p", col=1)

     lines(neo.edp2.rate$lambda ~ neo.edp2.rate$EDP, col=2,
         lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: EDP #2 rate calculations
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-2-rate
   #+RESULTS: edp-2-rate
   [[file:/tmp/babel-1752Epe/figure-1752vjD.pdf]]

\clearpage
* EDP #21
** EDP IM
   Read the EDP #21 IM data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp21.im <- read.csv(
         paste(results.dir, "edp-im-21", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp21.im) = c("IM", "mean_x", "sd_ln_x")

     neo.edp21.im <- read.csv("example1a_im_edp_21.txt",
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the mean and standard deviation:
   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(mean error) is %3.2f%%.", 
                 100 * max(abs(neo.edp21.im$mean_x - 
  				 paleo.edp21.im$mean_x)
  			 / paleo.edp21.im$mean_x)),
         sprintf("Mean (mean error) is %3.2f%%.", 
                 100 * mean((neo.edp21.im$mean_x - 
                                 paleo.edp21.im$mean_x)
  			  / paleo.edp21.im$mean_x)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R
     paste(
         sprintf("Max abs(sd_ln_x error) is %3.2f%%.", 
                 100 * max(abs(neo.edp21.im$sd_ln_x - 
    			       paleo.edp21.im$sd_ln_x)
    		       / paleo.edp21.im$sd_ln_x)),
         sprintf("Mean sd_ln_x error is %3.2f%%.", 
                 100 * mean((neo.edp21.im$sd_ln_x - 
    			       paleo.edp21.im$sd_ln_x)
    		       / paleo.edp21.im$sd_ln_x)),
         sep="\n")
   #+END_SRC

   Plot the mean (Figure [[fig:edp-21-im-mean]] and [[fig:edp-21-im-mean-zoom]]) and
   standard deviation (Figure [[fig:edp-21-im-sd-ln]]):d
   #+NAME: edp-21-im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
       palette(c("red", "blue"))
       plot(paleo.edp21.im$mean_x ~ paleo.edp21.im$IM, log="", 
  	  xlab="IM", ylab="EDP", main="mean(EDP 21)-IM",
	  lwd=5,
  	  type="p", col=1)

       lines(neo.edp21.im$mean_x ~ neo.edp21.im$IM, col=2, lwd=3)

       legend(x="right", legend=c("Paleo", "Neo"),
  	  fill=palette())
   #+END_SRC

   #+RESULTS:

   #+CAPTION: men(EDP #21) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-21-im-mean
   #+RESULTS: edp-21-im-mean
   [[file:/tmp/babel-1752Epe/figure-1752vVb.pdf]]

   #+NAME: edp-21-im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
     palette(c("red", "blue"))
     plot(paleo.edp21.im$mean_x ~ paleo.edp21.im$IM, log="", 
          xlab="IM", ylab="EDP", main="mean(EDP 21)-IM",
          lwd=5,
          xlim=c(0.8, 1.2),
          type="p", col=1)

     lines(neo.edp21.im$mean_x ~ neo.edp21.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+Caption: men(EDP #21) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-21-im-mean-zoom
   #+RESULTS: edp-21-im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752W0t.pdf]]

   #+NAME: edp-21-im-sd-ln
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp21.im$sd_ln_x ~ paleo.edp21.im$IM, log="", 
          xlab="IM", ylab="EDP", main="sd(ln(EDP 21))-IM",
          lwd=5,
          type="p", col=1)

     lines(neo.edp21.im$sd_ln_x ~ neo.edp21.im$IM, col=2,
  	 lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: sd(ln(EDP #21)) vs. IM
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-21-im-sd-ln
   #+RESULTS: edp-21-im-sd-ln
   [[file:/tmp/babel-1752Epe/figure-1752SrH.pdf]]

** EDP Rate
   Read the EDP #21 rate data:
   #+BEGIN_SRC R   :results output
     ## Read in the IM data:
     paleo.edp21.rate <- read.csv(
         paste(results.dir, "edp-21-rate.txt", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.edp21.rate) = c("EDP", "lambda")

     neo.edp21.rate <- read.csv("example1a_edp_21_rate.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   Compare the mean and standard deviation:
   #+BEGIN_SRC R   :results value 
     diff <- (paleo.edp21.rate$lambda
                  - neo.edp21.rate$lambda)
     diff.pct <- diff / paleo.edp21.rate$lambda
     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct))),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff), 
                 100 * mean(diff.pct)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 9.499000e-03 (8.23%). |
   | Mean error is 1.757726e-03 (0.58%).     |

   Plot the rate (Figure [[fig:edp-21-rate]]):
   #+NAME: edp-21-rate
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.edp21.rate$lambda ~ paleo.edp21.rate$EDP, log="xy", 
          xlab="EDP", ylab="lambda", main="EDP #21 Rate",
          lwd=5,
          type="p", col=1)

     lines(neo.edp21.rate$lambda ~ neo.edp21.rate$EDP, col=2,
         lwd=3)

     legend(x="topright", legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: EDP #21 rate calculations
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:edp-21-rate
   #+RESULTS: edp-21-rate
   [[file:/tmp/babel-1752Epe/figure-1752vjD.pdf]]

\clearpage
* COLLAPSE
  Read the COLLAPSE-IM data:
  #+BEGIN_SRC R   :results output
    ## Read in the IM data:
    paleo.collapse.im <- read.csv(
        paste(results.dir, "collapse-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.collapse.im) = c("IM", "pCollapse")

    paleo2.collapse.im <- read.csv(
        paste(results.dir, "collapse-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.collapse.im) = c("IM", "pCollapse")

    neo.collapse.im <- read.csv("example1a_collapse.txt", 
        header=TRUE, sep="")
    names(neo.collapse.im) = c("IM", "pCollapse")
  #+END_SRC
  
  #+RESULTS:

  Compare the two versions (assumes same IM values are used):
  #+BEGIN_SRC R :results value
    diff <- paleo.collapse.im$pCollapse -
        neo.collapse.im$pCollapse
    denom <- paleo.collapse.im$pCollapse
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %5.3e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e-05 (0.16%). |
  | Mean error is 3.850576e-07 (0.00%).     |

  Plot it:
  #+NAME: collapse-im
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM, 
         log="", lwd=5,
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
        col=2, lwd=3)

    points(paleo2.collapse.im$pCollapse ~ 
  	 paleo2.collapse.im$IM, col=3)


    legend(x="right",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Probability of Collapse calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im
  #+RESULTS: collapse-im
  [[file:/tmp/babel-1757XZc/figure-1757lVt.pdf]]

  #+NAME: collapse-im-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM, 
         log="y", lwd=5,
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         xlim=c(0, 0.5),
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
  	col=2)

    points(paleo2.collapse.im$pCollapse ~ 
  	 paleo2.collapse.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: COLLAPSE rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im-zoom
  #+RESULTS: collapse-im-zoom
  [[file:/tmp/babel-1752Epe/figure-17522vm.pdf]]

  #+NAME: collapse-im-zoom2
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM,
         log="y", lwd=5,
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         xlim=c(1.5, 2.0),
         ylim=c(0.9, 1.0),
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
  	col=2)

    points(paleo2.collapse.im$pCollapse ~
  	 paleo2.collapse.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: COLLAPSE rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im-zoom2
  #+RESULTS: collapse-im-zoom2
  [[file:/tmp/babel-1752Epe/figure-17527Cy.pdf]]

  
  The overall rate of collapse:
  #+BEGIN_SRC R  :results value 
    paleo.rate <- scan(paste(results.dir, "collapse-rate", 
                             sep=""), skip=3)
    paleo2.rate <- scan(paste(results2.dir, "collapse-rate", 
                              sep=""), skip=3)
    neo.rate <- as.numeric(scan("example1a_collrate.txt", 
                                what="string")[8])
    paste(
        sprintf("Paleo: %5.3e; Neo: %5.3e; error: %3.2f%%", 
                paleo.rate,
                neo.rate, 
                (100*abs(neo.rate - paleo.rate)/paleo.rate)),
        sprintf("Paleo: %5.3e; Paleo2: %5.3e; error: %3.2f%%", 
                paleo.rate,
                paleo2.rate, 
                (100*abs(paleo2.rate-paleo.rate)/paleo.rate)),
        sep="\n")
  #+END_SRC
  
  #+RESULTS:
  | Paleo: 2.125500e-04; Neo: 2.158956e-04; error: 1.57%    |
  | Paleo: 2.125500e-04; Paleo2: 2.125500e-04; error: 0.00% |

\clearpage
* PG #1
** LOSS-IM
   Read the LOSS-IM data for group #1:
   #+BEGIN_SRC R   :results output
     paleo.loss1.im <- read.csv(
         paste(results.dir, "pg-1-im", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss1.im) = c("IM", "mean_x", "sd_ln_x")

     neo.loss1.im <- read.csv("example1a_loss_1_im.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the mean error:
   #+BEGIN_SRC R 
     diff <- paleo.loss1.im$mean_x - neo.loss1.im$mean_x
     denom <- paleo.loss1.im$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 2.100e-01 (1.06%). |
   | Mean error is -1.241e-02 (-0.06%).   |

   Plot the mean (Figures [[fig:loss1.im-mean]] and [[fig:loss1.im-mean-zoom]]):
   #+NAME: loss1.im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.loss1.im$mean_x ~ paleo.loss1.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss1.im$mean_x ~ neo.loss1.im$IM, col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (Group #1)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.im-mean
   #+RESULTS: loss1.im-mean
   [[file:/tmp/babel-1752Epe/figure-1752u3v.pdf]]

   #+NAME: loss1.im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.loss1.im$mean_x ~ paleo.loss1.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
	  xlim=c(0.001, 0.10), ylim=c(1, 20),
          type="p", col=1)

     lines(neo.loss1.im$mean_x ~ neo.loss1.im$IM, col=2)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (Group #1)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.im-mean-zoom
   #+RESULTS: loss1.im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752POp.pdf]]

   #+BEGIN_SRC R 
     diff <- paleo.loss1.im$sd_ln_x - neo.loss1.im$sd_ln_x
     denom <- paleo.loss1.im$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC


   #+NAME: loss1.im-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss1.im$sd_ln_x ~ paleo.loss1.im$IM, log="", 
          xlab="IM", ylab="sd(ln(Loss))", 
          main="Loss-IM Relationship",
          type="p", col=1)

     lines(neo.loss1.im$sd_ln_x ~ neo.loss1.im$IM, col=2)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: LOSS1.IM rate calculations (Group #1)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.im-sd
   #+RESULTS: loss1.im-sd
   [[file:/tmp/babel-1752Epe/figure-17521AR.pdf]]

** LOSS-EDP
   Read the LOSS-EDP data for group #1:
   #+BEGIN_SRC R   :results output
     paleo.loss1.edp <- read.csv(
         paste(results.dir, "pg-1-edp", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss1.edp) = c("EDP", "mean_x", "sd_ln_x")

     neo.loss1.edp <- read.csv("example1a_loss_1_edp.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.loss1.edp$mean_x - neo.loss1.edp$mean_x
     denom <- paleo.loss1.edp$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R 
     diff <- paleo.loss1.edp$sd_ln_x - neo.loss1.edp$sd_ln_x
     denom <- paleo.loss1.edp$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   Plot the mean (Figures [[fig:loss1.edp-mean]] and [[fig:loss1.edp-mean-zoom]]) and
   standard deviation (Figure [[fig:loss1.edp-sd]]):
   #+NAME: loss1.edp-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R
     palette(c("red", "blue", "green"))
     plot(paleo.loss1.edp$mean_x ~ paleo.loss1.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
          main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss1.edp$mean_x ~ neo.loss1.edp$EDP, 
         col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC
   #+CAPTION: Loss-EDP rate calculations (group #1)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.edp-mean
   #+RESULTS: loss1.edp-mean
   [[file:/tmp/babel-1752Epe/figure-17529OM.pdf]]

   #+NAME: loss1.edp-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss1.edp$mean_x ~ paleo.loss1.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
	  main="Loss-EDP Relationship",
          xlim=c(0.05, 0.10),
          type="p", col=1, lwd=5)

     lines(neo.loss1.edp$mean_x ~ neo.loss1.edp$EDP, 
  	 col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC
l
   #+CAPTION: Loss-EDP rate calculations (group #1)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.edp-mean-zoom
   #+RESULTS: loss1.edp-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752KgG.pdf]]



   #+NAME: loss1.edp-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss1.edp$sd_ln_x ~ paleo.loss1.edp$EDP, log="", 
          xlab="EDP", ylab="sd(ln(Loss))",
	  main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss1.edp$sd_ln_x ~ neo.loss1.edp$EDP, 
  	 col=2, lwd=3)

     points(paleo.loss1.edp$sd_ln_x ~ paleo.loss1.edp$EDP, col=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP calculations
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss1.edp-sd
   #+RESULTS: loss1.edp-sd
   [[file:/tmp/babel-1752Epe/figure-1752-If.pdf]]


\clearpage
* PG #2
** LOSS-IM
   Read the LOSS-IM data for group #2:
   #+BEGIN_SRC R   :results output
     paleo.loss2.im <- read.csv(
         paste(results.dir, "pg-2-im", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss2.im) = c("IM", "mean_x", "sd_ln_x")

     neo.loss2.im <- read.csv("example1a_loss_2_im.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.loss2.im$mean_x - neo.loss2.im$mean_x
     denom <- paleo.loss2.im$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R 
     diff <- paleo.loss2.im$sd_ln_x - neo.loss2.im$sd_ln_x
     denom <- paleo.loss2.im$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.763e+00 (100.00%). |
   | Mean error is 7.713e-02 (1.43%).       |



   Plot the mean (Figures [[fig:loss2.im-mean]] and [[fig:loss2.im-mean-zoom]]) and
   standard deviation (Figures [[fig:loss2.im-sd]] and [[fig:loss2.im-sd-zoom]]):
   #+NAME: loss2.im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.im$mean_x ~ paleo.loss2.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss2.im$mean_x ~ neo.loss2.im$IM, col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.im-mean
   #+RESULTS: loss2.im-mean
   [[file:/tmp/babel-1752Epe/figure-1752h0d.pdf]]

   #+NAME: loss2.im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.im$mean_x ~ paleo.loss2.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
	  xlim=c(0.10, 0.30), 
          type="p", col=1)

     lines(neo.loss2.im$mean_x ~ neo.loss2.im$IM, col=2)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.im-mean-zoom
   #+RESULTS: loss2.im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752LaZ.pdf]]


   #+NAME: loss2.im-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.im$sd_ln_x ~ paleo.loss2.im$IM, log="", 
          xlab="IM", ylab="sd(ln(Loss))", 
          main="Loss-IM Relationship",
          type="p", col=1)

     lines(neo.loss2.im$sd_ln_x ~ neo.loss2.im$IM, col=2)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: LOSS2.IM rate calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.im-sd
   #+RESULTS: loss2.im-sd
   [[file:/tmp/babel-1752Epe/figure-17521hg.pdf]]

   #+NAME: loss2.im-sd-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.im$sd_ln_x ~ paleo.loss2.im$IM, log="", 
          xlab="IM", ylab="sd(ln(Loss))",
	  xlim=c(0.01, 0.30),
          main="Loss-IM Relationship",
          type="p", col=1)

     lines(neo.loss2.im$sd_ln_x ~ neo.loss2.im$IM, col=2)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: LOSS2.IM rate calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.im-sd-zoom
   #+RESULTS: loss2.im-sd-zoom
   [[file:/tmp/babel-1752Epe/figure-1752P9g.pdf]]

** LOSS-EDP
   Read the LOSS-EDP data for group #2:
   #+BEGIN_SRC R   :results output
     paleo.loss2.edp <- read.csv(
         paste(results.dir, "pg-2-edp", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss2.edp) = c("EDP", "mean_x", "sd_ln_x")

     neo.loss2.edp <- read.csv("example1a_loss_2_edp.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.loss2.edp$mean_x - neo.loss2.edp$mean_x
     denom <- paleo.loss2.edp$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.000000e-05 (0.03%). |
   | Mean error is 1.506201e-06 (0.00%).     |

   #+BEGIN_SRC R 
     diff <- paleo.loss2.edp$sd_ln_x - neo.loss2.edp$sd_ln_x
     denom <- paleo.loss2.edp$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.000000e-04 (0.05%). |
   | Mean error is 4.953020e-06 (0.00%).     |

   Plot the means (Figures [[fig:loss2.edp-mean]] and [[fig:loss2.edp-mean-zoom]]) and
   standard deviation (Figures [[fig:loss2.edp-sd]] and [[fig:loss2.edp-sd-zoom]]):
   #+NAME: loss2.edp-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.edp$mean_x ~ paleo.loss2.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
          main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss2.edp$mean_x ~ neo.loss2.edp$EDP, 
         col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP rate calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.edp-mean
   #+RESULTS: loss2.edp-mean
   [[file:/tmp/babel-1752Epe/figure-1752NDI.pdf]]

   #+NAME: loss2.edp-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.edp$mean_x ~ paleo.loss2.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
	  main="Loss-EDP Relationship",
          xlim=c(0.05, 0.10),
          type="p", col=1, lwd=5)

     lines(neo.loss2.edp$mean_x ~ neo.loss2.edp$EDP, 
  	 col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC
   #+CAPTION: Loss-EDP rate calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.edp-mean-zoom
   #+RESULTS: loss2.edp-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752_Cy.pdf]]



   #+NAME: loss2.edp-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.edp$sd_ln_x ~ paleo.loss2.edp$EDP, log="", 
          xlab="EDP", ylab="sd(ln(Loss))",
	  main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)
     lines(neo.loss2.edp$sd_ln_x ~ neo.loss2.edp$EDP, 
  	 col=2, lwd=3)

     points(paleo.loss2.edp$sd_ln_x ~ paleo.loss2.edp$EDP, col=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.edp-sd
   #+RESULTS: loss2.edp-sd
   [[file:/tmp/babel-1752Epe/figure-1752ofP.pdf]]


   #+NAME: loss2.edp-sd-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
     palette(c("red", "blue", "green"))
     plot(paleo.loss2.edp$sd_ln_x ~ paleo.loss2.edp$EDP, log="", 
          xlab="EDP", ylab="sd(ln(Loss))",
	  main="Loss-EDP Relationship",
          xlim=c(0.08, 0.12),
          type="p", col=1, lwd=5)

     lines(neo.loss2.edp$sd_ln_x ~ neo.loss2.edp$EDP, 
  	 col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP calculations (group #2)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss2.edp-sd-zoom
   #+RESULTS: loss2.edp-sd-zoom
   [[file:/tmp/babel-1752Epe/figure-1752MUs.pdf]]

\clearpage
* PG #31
** LOSS-IM
   Read the LOSS-IM data for group #31:
   #+BEGIN_SRC R   :results output
     paleo.loss31.im <- read.csv(
         paste(results.dir, "pg-31-im", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss31.im) = c("IM", "mean_x", "sd_ln_x")

     neo.loss31.im <- read.csv("example1a_loss_31_im.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.loss31.im$mean_x - neo.loss31.im$mean_x
     denom <- paleo.loss31.im$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+BEGIN_SRC R 
     diff <- paleo.loss31.im$sd_ln_x - neo.loss31.im$sd_ln_x
     denom <- paleo.loss31.im$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.763e+00 (100.00%). |
   | Mean error is 7.713e-02 (1.43%).       |



   Plot the mean (Figures [[fig:loss31.im-mean]] and [[fig:loss31.im-mean-zoom]]) and
   standard deviation (Figures [[fig:loss31.im-sd]] and [[fig:loss31.im-sd-zoom]]):
   #+NAME: loss31.im-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.im$mean_x ~ paleo.loss31.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss31.im$mean_x ~ neo.loss31.im$IM, col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.im-mean
   #+RESULTS: loss31.im-mean
   [[file:/tmp/babel-1752Epe/figure-1752h0d.pdf]]

   #+NAME: loss31.im-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.im$mean_x ~ paleo.loss31.im$IM, log="y", 
          xlab="IM", ylab="Mean Loss",
	  main="Loss-IM Relationship",
	  xlim=c(0.10, 0.30), 
          type="p", col=1)

     lines(neo.loss31.im$mean_x ~ neo.loss31.im$IM, col=2)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-IM calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.im-mean-zoom
   #+RESULTS: loss31.im-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752LaZ.pdf]]


   #+NAME: loss31.im-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.im$sd_ln_x ~ paleo.loss31.im$IM, log="", 
          xlab="IM", ylab="sd(ln(Loss))", 
          main="Loss-IM Relationship",
          type="p", col=1)

     lines(neo.loss31.im$sd_ln_x ~ neo.loss31.im$IM, col=2)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: LOSS31.IM rate calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.im-sd
   #+RESULTS: loss31.im-sd
   [[file:/tmp/babel-1752Epe/figure-17521hg.pdf]]

   #+NAME: loss31.im-sd-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.im$sd_ln_x ~ paleo.loss31.im$IM, log="", 
          xlab="IM", ylab="sd(ln(Loss))",
	  xlim=c(0.01, 0.30),
          main="Loss-IM Relationship",
          type="p", col=1)

     lines(neo.loss31.im$sd_ln_x ~ neo.loss31.im$IM, col=2)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: LOSS31.IM rate calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.im-sd-zoom
   #+RESULTS: loss31.im-sd-zoom
   [[file:/tmp/babel-1752Epe/figure-1752P9g.pdf]]

** LOSS-EDP
   Read the LOSS-EDP data for group #31:
   #+BEGIN_SRC R   :results output
     paleo.loss31.edp <- read.csv(
         paste(results.dir, "pg-31-edp", sep=""),
         skip=3, header=FALSE, sep="")
     names(paleo.loss31.edp) = c("EDP", "mean_x", "sd_ln_x")

     neo.loss31.edp <- read.csv("example1a_loss_31_edp.txt", 
         header=TRUE, sep="")
   #+END_SRC
  
   #+RESULTS:

   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.loss31.edp$mean_x - neo.loss31.edp$mean_x
     denom <- paleo.loss31.edp$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.000000e-05 (0.03%). |
   | Mean error is 1.506201e-06 (0.00%).     |

   #+BEGIN_SRC R 
     diff <- paleo.loss31.edp$sd_ln_x - neo.loss31.edp$sd_ln_x
     denom <- paleo.loss31.edp$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n")
   #+END_SRC

   #+RESULTS:
   | Max abs(error) is 5.000000e-04 (0.05%). |
   | Mean error is 4.953020e-06 (0.00%).     |

   Plot the means (Figures [[fig:loss31.edp-mean]] and [[fig:loss31.edp-mean-zoom]]) and
   standard deviation (Figures [[fig:loss31.edp-sd]] and [[fig:loss31.edp-sd-zoom]]):
   #+NAME: loss31.edp-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.edp$mean_x ~ paleo.loss31.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
          main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)

     lines(neo.loss31.edp$mean_x ~ neo.loss31.edp$EDP, 
         col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP rate calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.edp-mean
   #+RESULTS: loss31.edp-mean
   [[file:/tmp/babel-1752Epe/figure-1752NDI.pdf]]

   #+NAME: loss31.edp-mean-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.edp$mean_x ~ paleo.loss31.edp$EDP, log="xy", 
          xlab="EDP", ylab="Mean(Loss)",
	  main="Loss-EDP Relationship",
          xlim=c(0.05, 0.10),
          type="p", col=1, lwd=5)

     lines(neo.loss31.edp$mean_x ~ neo.loss31.edp$EDP, 
  	 col=2, lwd=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC
   #+CAPTION: Loss-EDP rate calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.edp-mean-zoom
   #+RESULTS: loss31.edp-mean-zoom
   [[file:/tmp/babel-1752Epe/figure-1752_Cy.pdf]]



   #+NAME: loss31.edp-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.edp$sd_ln_x ~ paleo.loss31.edp$EDP, log="", 
          xlab="EDP", ylab="sd(ln(Loss))",
	  main="Loss-EDP Relationship",
          type="p", col=1, lwd=5)
     lines(neo.loss31.edp$sd_ln_x ~ neo.loss31.edp$EDP, 
  	 col=2, lwd=3)

     points(paleo.loss31.edp$sd_ln_x ~ paleo.loss31.edp$EDP, col=3)

     legend(x="right",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.edp-sd
   #+RESULTS: loss31.edp-sd
   [[file:/tmp/babel-1752Epe/figure-1752ofP.pdf]]


   #+NAME: loss31.edp-sd-zoom
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R 
     palette(c("red", "blue", "green"))
     plot(paleo.loss31.edp$sd_ln_x ~ paleo.loss31.edp$EDP, log="", 
          xlab="EDP", ylab="sd(ln(Loss))",
	  main="Loss-EDP Relationship",
          xlim=c(0.08, 0.12),
          type="p", col=1, lwd=5)

     lines(neo.loss31.edp$sd_ln_x ~ neo.loss31.edp$EDP, 
  	 col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Loss-EDP calculations (group #31)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:loss31.edp-sd-zoom
   #+RESULTS: loss31.edp-sd-zoom
   [[file:/tmp/babel-1752Epe/figure-1752MUs.pdf]]

\clearpage
* Total Loss
  Read the Total Loss data:
  #+BEGIN_SRC R   :results output
    paleo.structloss.c <- read.csv(
        paste(results.dir, "tlossc", sep=""),
         skip=3, header=FALSE, sep="")
    names(paleo.structloss.c) = c("IM", "mean_x", "sd_ln_x")

    paleo.structloss.nc <- read.csv(
        paste(results.dir, "tlossnc", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.structloss.nc) = c("IM", "mean_x", "sd_ln_x")

    neo.structloss.c <- read.csv("example1a_loss_c_total", 
        header=TRUE, sep="")

    neo.structloss.nc <- read.csv("example1a_loss_nc_total", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:
** Non-Collapse
   Compare the means and standard deviations:
   #+BEGIN_SRC R
     diff <- paleo.structloss.nc$mean_x -
         neo.structloss.nc$mean_x
     denom <- paleo.structloss.nc$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("mean valus:"),
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),

         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n    ")
   #+END_SRC

   #+RESULTS:
   | mean valus:                          |
   | Max abs(error) is 1.525e-01 (0.67%). |
   | Mean error is -4.376e-03 (-0.02%).   |

   #+BEGIN_SRC R 
     diff <- paleo.structloss.nc$sd_ln_x - 
         neo.structloss.nc$sd_ln_x
     denom <- paleo.structloss.nc$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("standard deviations:"),
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n   ")
   #+END_SRC

   #+RESULTS:
   | standard deviations:                  |
   | Max abs(error) is 6.151e-02 (14.33%). |
   | Mean error is -4.376e-02 (-10.51%).   |

   Plot the mean (Figure [[fig:structloss.nc-mean]]) and standard deviation (Figure
   [[fig:structloss.nc-sd]]):
   #+NAME: structloss.nc-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R
     palette(c("red", "blue"))
     plot(paleo.structloss.nc$mean_x ~
          paleo.structloss.nc$IM, log="",
	  xlim=c(0, 1.5), ylim=c(0, 10E6),
          xlab="IM", ylab="Mean(Loss)", 
          main="Total Loss, No Collapse",
          type="p", col=1, lwd=5)

     lines(neo.structloss.nc$mean_x ~ neo.structloss.nc$IM, 
         col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Mean Total Loss 
   #+CAPTION: (*not* considering collapse)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.nc-mean
   #+RESULTS: structloss.nc-mean
   [[file:/tmp/babel-1757XZc/figure-17572zh.pdf]]


   #+NAME: structloss.nc-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.structloss.nc$sd_ln_x ~ paleo.structloss.nc$IM,
          log="", xlab="IM", ylab="sd(ln(Loss))", 
          main="Total Loss, No Collapse",
          type="p", col=1, lwd=5)
     lines(neo.structloss.nc$sd_ln_x ~ neo.structloss.nc$IM, 
         col=2, lwd=3)
  
     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Standard deviation of total loss
   #+CAPTION: (*not* considering collapse)
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.nc-sd
   #+RESULTS: structloss.nc-sd
   [[file:/tmp/babel-1757XZc/figure-17576YY.pdf]]


** Collapse
   Compare the means and standard deviations:
   #+BEGIN_SRC R 
     diff <- paleo.structloss.c$mean_x - 
         neo.structloss.c$mean_x
     denom <- paleo.structloss.c$mean_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Mean loss, considering collapse:"),
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n    ")
   #+END_SRC

   #+RESULTS:
   | Mean loss, considering collapse:     |
   | Max abs(error) is 1.203e-01 (0.62%). |
   | Mean error is -1.849e-03 (-0.01%).   |

   #+BEGIN_SRC R 
     diff <- paleo.structloss.c$sd_ln_x - 
         neo.structloss.c$sd_ln_x
     denom <- paleo.structloss.c$sd_ln_x
     denom[denom == 0] <- NA
     diff.pct <- diff / denom

     paste(
         sprintf("Standard Deviation of loss, considering collapse:"),
         sprintf("Max abs(error) is %5.3e (%3.2f%%).",
                 max(abs(diff)),
                 100 * max(abs(diff.pct), na.rm=TRUE)),
         sprintf("Mean error is %5.3e (%3.2f%%).",
                 mean(diff),
                 100 * mean(diff.pct, na.rm=TRUE)),
         sep="\n    ")
   #+END_SRC

   #+RESULTS:
   | Standard Deviation of loss, considering collapse: |
   | Max abs(error) is 4.402e-02 (8.88%).              |
   | Mean error is -1.777e-02 (-3.56%).                |

   Plot the mean (Figure [[fig:structloss.c-mean]]) and standard deviation (Figure
   [[fig:structloss.c-sd]]):
   #+NAME: structloss.c-mean
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R
     palette(c("red", "blue"))
     plot(paleo.structloss.c$mean_x ~ paleo.structloss.c$IM, 
          log="", xlab="IM", ylab="Mean(Loss)",
	  xlim=c(0, 1.5), ylim=c(0, 20E6),
          main="Total Loss, Collapse",
          type="p", col=1, lwd=5)

     lines(neo.structloss.c$mean_x ~ neo.structloss.c$IM, 
         col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Mean of total loss, considering collapse.
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.c-mean
   #+RESULTS: structloss.c-mean
   [[file:/tmp/babel-1757XZc/figure-1757CLJ.pdf]]


   #+NAME: structloss.c-sd
   #+HEADER: :results graphics
   #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
   #+BEGIN_SRC R  
     palette(c("red", "blue"))
     plot(paleo.structloss.c$sd_ln_x ~ paleo.structloss.c$IM, log="", 
          xlab="EDP", ylab="sd(ln(Loss))", main="Total Loss, Collapse",
	  ylim=c(0, max(paleo.structloss.c$sd_ln_x)),
          type="p", col=1, lwd=5)
     lines(neo.structloss.c$sd_ln_x ~ neo.structloss.c$IM, 
  	 col=2, lwd=3)

     legend(x="topright",
          legend=c("Paleo", "Neo"),
          fill=palette())
   #+END_SRC

   #+CAPTION: Standard deviation of loss, considering collapse
   #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
   #+NAME: fig:structloss.c-sd
   #+RESULTS: structloss.c-sd
   [[file:/tmp/babel-1752Epe/figure-1752gLO.pdf]]


** Temp								   :noexport:
   EDP-IM relationships:
   #+BEGIN_SRC sh :results output
   for i in $(seq 21); do    
      f=example1a_im_edp_${i}.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/edp-im-${i}
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
#+end_example

   EDP-rate relationships
   #+BEGIN_SRC sh :results output
   for i in $(seq 21); do    
      f=example1a_edp_${i}_rate.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/edp-${i}-rate.txt
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   0.001 1.0000E-03 ;  0.15 0.1500 ;  149 149
   0.001 1.0000E-03 ;  0.1 0.1000 ;  149 149
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
#+end_example

   Loss-edp
   #+BEGIN_SRC sh :results output
   for i in $(seq 115); do    
      f=example1a_loss_${i}_edp.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/pg-${i}-edp
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $i":" $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   1: 0.001 1.0000E-03 ;  0.1 0.1000 ;  149 149
   2: 0.001 1.0000E-03 ;  0.1 0.1000 ;  149 149
   3: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   4: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   5: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   6: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   7: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   8: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   9: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   10: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   11: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   12: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   13: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   14: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   15: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   16: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   17: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   18: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   19: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   20: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   21: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 149
   22: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   23: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   24: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   25: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   26: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   27: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   28: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   29: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   30: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   31: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 149
   32: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   33: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   34: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   35: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   36: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   37: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   38: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   39: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   40: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   41: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 149
   42: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   43: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   44: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   45: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   46: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   47: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   48: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   49: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   50: 0.001 1.0000E-03 ;  0.1 0.1000 ;  199 199
   51: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   52: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   53: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   54: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   55: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   56: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   57: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   58: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   59: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   60: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   61: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   62: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   63: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   64: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   65: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   66: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   67: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   68: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   69: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   70: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   71: 0.001 1.0000E-03 ;  0.1 0.1500 ;  199 149
   72: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   73: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   74: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   75: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   76: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   77: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   78: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   79: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   80: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   81: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   82: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   83: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   84: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   85: 0.05 1.0000E-03 ;  5.0 0.1500 ;  199 149
   86: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 149
   87: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   88: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   89: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   90: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   91: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   92: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   93: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   94: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   95: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   96: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 149
   97: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   98: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   99: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   100: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   101: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   102: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   103: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   104: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   105: 0.05 1.0000E-03 ;  5.0 0.1000 ;  199 199
   106: 0.05 1.0000E-03 ;  5.0 0.1500 ;  199 149
   107: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   108: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   109: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   110: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   111: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   112: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   113: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   114: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
   115: 0.05 5.0000E-02 ;  5.0 5.000 ;  199 199
#+end_example

   Loss-im
   #+BEGIN_SRC sh :results output
   for i in $(seq 115); do    
      f=example1a_loss_${i}_im.txt
      min_n=$(head -2 $f | tail -1 | awk -e '{print $1}')
      max_n=$(tail -1 $f | awk -e '{print $1}')
      count_n=$(wc -l $f | awk -e '{print $1 - 1}')

      f=~/SLATv1.15_Public/example1a_collapse/results/pg-${i}-im
      min_p=$(head -4 $f | tail -1 | awk -e '{print $1}')
      max_p=$(tail -2 $f | awk -e 'BEGIN{RS="\r\n"} {print $1}')
      count_p=$(wc -l $f | awk -e '{print $1 - 4}')
      echo $min_n $min_p "; " $max_n $max_p "; " $count_n $count_p
   done
   #+END_SRC

   #+RESULTS:
   #+begin_example
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
   0.01 1.0000E-02 ;  2.5 2.500 ;  199 199
#+end_example

