#+Title:     SLAT: Example 1 with Collapse Added
#+AUTHOR:    Michael Gauland
#+EMAIL:     michael.gauland@canterbury.ac.nz
#+DATE:      {{{time(%Y-%m-%d %H:%M)}}}
#+DESCRIPTION: 
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:6 num:t toc:4 \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:dvipng LaTeX:dvipng skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   timestamp:t email:t
#+OPTIONS:   ':t
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{unicode-math}
#+LaTex_header: \usepackage{epstopdf}
#+LATEX_HEADER: \usepackage{register}
#+LATEX_HEADER: \usepackage{bytefield}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{tabulary}
#+LATEX_HEADER: \usepackage[section]{placeins}
#+LATEX_HEADER: \usepackage[htt]{hyphenat}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \lstset{keywordstyle=\color{blue}\bfseries}
#+LATEX_HEADER: \newfontfamily\listingsfont[Scale=.7]{DejaVu Sans Mono}
#+LATEX_HEADER: \lstset{basicstyle=\listingsfont}
#+LATEX_HEADER: \lstset{showspaces=false}
#+LATEX_HEADER: \lstset{columns=fixed}
#+LATEX_HEADER: \lstset{extendedchars=true}
#+LATEX_HEADER: \lstset{frame=shadowbox}
#+LATEX_HEADER: \lstset{basicstyle=\ttfamily}
#+LATEX_HEADER: \definecolor{mygray}{gray}{0.8}
#+LATEX_HEADER: \lstset{rulesepcolor=\color{mygray}}
#+LATEX_HEADER: \lstdefinelanguage{dash}{rulecolor=\color{green},rulesepcolor=\color{mygray},frameround=ffff,backgroundcolor=\color{white}}
#+LATEX_HEADER: \lstdefinelanguage{fundamental}{basicstyle=\ttfamily\scriptsize,rulesepcolor=\color{cyan},frameround=tttt,backgroundcolor=\color{white},breaklines=true}
#+LATEX_HEADER: \usepackage{pst-circ}
#+LATEX_HEADER: \usepackage[hang,small,bf]{caption}
#+LATEX_HEADER: \setlength{\captionmargin}{20pt}
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+STARTUP: overview
#+STARTUP: align
#+STARTUP: noinlineimages
#+PROPERTY: header-args:R  :session *R-1*
#+PROPERTY: header-args    :exports both

\clearpage
* Initialisation
  The code in this section reads in the input data, as well as the results
  produces by the old ("paleo") and new ("neo") versions of SLAT.

  Set up variables to make it easier to get to the files:
  #+BEGIN_SRC R  :results output
    paleo.dir = paste("~/SLATv1.15_Public/",
	"example1a_collapse/", sep="")
    results.dir = paste(paleo.dir, "results/", sep="")

    paleo2.dir = paste("~/SLATv1.15_Public/",
	"example2_10storeybuilding/", sep="")
    results2.dir = paste(paleo2.dir, "results/", sep="")
  #+END_SRC

  #+RESULTS:
  
* IM
  Read the IM rate data:
  #+BEGIN_SRC R  :results output
    ## Read in the IM data:
    paleo.im <- read.csv(
        paste(results.dir, "im-rate.txt", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.im) = c("IM", "lambda")


    paleo2.im <- read.csv(
        paste(results2.dir, "im-rate", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.im) = c("IM", "lambda")

    neo.im <- read.csv("example1a_im_rate", 
                       header=TRUE, sep="")

    input.im <- read.csv(
        paste(paleo.dir, "IMrateSa15data.txt", sep=""),
        skip=2, header=FALSE, sep="")
    names(input.im) = c("IM", "lambda")
  #+END_SRC
  
  #+RESULTS:

  Plot it (Figure [[fig:im-rate]]):
  #+NAME: im-rate
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R
     palette(c("red", "blue", "green", "cyan"))
     plot(paleo.im$lambda ~ paleo.im$IM, log="xy", 
  	xlab="IM", ylab="lambda", main="IM Rate",
  	type="l", lwd=5, col=1,
  	xlim=c(0.01, 3.0), ylim=c(1E-8, 1E0),
  	pch=25)

    lines(neo.im$lambda ~ neo.im$IM, lwd=3, col=2, pch=24)

    points(input.im$lambda ~ input.im$IM, col=3)

    lines(paleo2.im$lambda ~ paleo2.im$IM, col=4, lwd=1)

    legend(x="topright",
  	 legend=c("Paleo", "Neo", "Input", "Paleo2"),
  	 fill=palette())
  #+END_SRC

  #+CAPTION: IM rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:im-rate
  #+RESULTS: im-rate
  [[file:/tmp/babel-1752Epe/figure-1752IwU.pdf]]

  Compare the two versions (assumes same IM values are used):
  #+BEGIN_SRC R
    sprintf("Max difference is %3.2f%%",
        100 * max(abs(paleo.im$lambda - neo.im$lambda)
  		/ paleo.im$lambda))
  #+END_SRC

  #+RESULTS:
  : Max difference is 100.00%


* EDP IM
  Read the EDP IM data:
  #+BEGIN_SRC R   :results output
    ## Read in the IM data:
    paleo.edp.im <- read.csv(
        paste(results.dir, "edp-im-1", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.edp.im) = c("IM", "mean_x", "sd_ln_x")

    paleo2.edp.im <- read.csv(
        paste(results.dir, "edp-im-1", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.edp.im) = c("IM", "mean_x", "sd_ln_x")

    neo.edp.im <- read.csv("example1a_im_edp.txt",
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:

  #+BEGIN_SRC R
    paste(
        sprintf("Max abs(mean error) is %3.2f%%.", 
                100 * max(abs(neo.edp.im$mean_x - 
  				paleo.edp.im$mean_x)
  			/ paleo.edp.im$mean_x)),
        sprintf("Mean (mean error) is %3.2f%%.", 
                100 * mean((neo.edp.im$mean_x - 
                                paleo.edp.im$mean_x)
  			 / paleo.edp.im$mean_x)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(mean error) is 0.05%. |
  | Mean (mean error) is 0.00%.   |

  #+BEGIN_SRC R
    paste(
        sprintf("Max abs(sd_ln_x error) is %3.2f%%.", 
                100 * max(abs(neo.edp.im$sd_ln_x - 
    			      paleo.edp.im$sd_ln_x)
    		      / paleo.edp.im$sd_ln_x)),
        sprintf("Mean sd_ln_x error is %3.2f%%.", 
                100 * mean((neo.edp.im$sd_ln_x - 
    			      paleo.edp.im$sd_ln_x)
    		      / paleo.edp.im$sd_ln_x)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(sd_ln_x error) is 1.21%. |
  | Mean sd_ln_x error is 0.03%.     |

  Plot it (Figure [[fig:edp-im-mean]]):
  #+NAME: edp-im-mean
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
      palette(c("red", "blue", "green"))
      plot(paleo.edp.im$mean_x ~ paleo.edp.im$IM, log="", 
  	 xlab="IM", ylab="EDP", main="mean(EDP)-IM",
	 lwd=5,
  	 type="p", col=1)

      lines(neo.edp.im$mean_x ~ neo.edp.im$IM, col=2, lwd=3)

      points(paleo2.edp.im$mean_x ~ paleo2.edp.im$IM,
          col=3)

      legend(x="right",
  	 legend=c("Paleo", "Neo", "Paleo2"),
  	 fill=palette())
  #+END_SRC

  #+RESULTS:

  #+CAPTION: men(EDP) vs. IM
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:edp-im-mean
  #+RESULTS: edp-im-mean
  [[file:/tmp/babel-1752Epe/figure-1752vVb.pdf]]

  #+NAME: edp-im-mean-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.edp.im$mean_x ~ paleo.edp.im$IM, log="", 
         xlab="IM", ylab="EDP", main="mean(EDP)-IM",
         lwd=5,
         xlim=c(0.8, 1.2),
         type="p", col=1)

    lines(neo.edp.im$mean_x ~ neo.edp.im$IM, col=2,
  	lwd=3)

    points(paleo2.edp.im$mean_x ~ paleo2.edp.im$IM,
  	col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+Caption: men(EDP) vs. IM
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:edp-im-mean-zoom
  #+RESULTS: edp-im-mean-zoom
  [[file:/tmp/babel-1752Epe/figure-1752W0t.pdf]]

  #+NAME: edp-im-sd-ln
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.edp.im$sd_ln_x ~ paleo.edp.im$IM, log="", 
         xlab="IM", ylab="EDP", main="sd(ln(EDP))-IM",
         lwd=5,
         type="p", col=1)

    lines(neo.edp.im$sd_ln_x ~ neo.edp.im$IM, col=2,
  	lwd=3)

    points(paleo2.edp.im$sd_ln_x ~ paleo2.edp.im$IM,
  	 col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: sd(ln(EDP)) vs. IM
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:edp-im-sd-ln
  #+RESULTS: edp-im-sd-ln
  [[file:/tmp/babel-1752Epe/figure-1752SrH.pdf]]

* EDP Rate
  Read the EDP rate data:
  #+BEGIN_SRC R   :results output
    ## Read in the IM data:
    paleo.edp.rate <- read.csv(
        paste(results.dir, "edp-rate.txt", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.edp.rate) = c("EDP", "lambda")

    paleo2.edp.rate <- read.csv(
        paste(results.dir, "edp-rate.txt", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.edp.rate) = c("EDP", "lambda")

    neo.edp.rate <- read.csv("example1a_edp_rate.txt", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:

  #+BEGIN_SRC R   :results value 
    diff <- (paleo.edp.rate$lambda
                 - neo.edp.rate$lambda)
    diff.pct <- diff / paleo.edp.rate$lambda
    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct))),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff), 
                100 * mean(diff.pct)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 9.499000e-03 (8.23%). |
  | Mean error is 1.757726e-03 (0.58%).     |

  Plot it (Figure [[fig:edp-rate]]):
  #+NAME: edp-rate
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.edp.rate$lambda ~ paleo.edp.rate$EDP, log="xy", 
         xlab="EDP", ylab="lambda", main="EDP Rate",
         lwd=5,
         type="p", col=1)

    lines(neo.edp.rate$lambda ~ neo.edp.rate$EDP, col=2,
        lwd=3)

    points(paleo2.edp.rate$lambda ~ paleo2.edp.rate$EDP,
  	 col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: EDP rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:edp-rate
  #+RESULTS: edp-rate
  [[file:/tmp/babel-1752Epe/figure-1752vjD.pdf]]

* COLLAPSE
  Read the COLLAPSE-IM data:
  #+BEGIN_SRC R   :results output
    ## Read in the IM data:
    paleo.collapse.im <- read.csv(
        paste(results.dir, "collapse-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.collapse.im) = c("IM", "pCollapse")

    paleo2.collapse.im <- read.csv(
        paste(results.dir, "collapse-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.collapse.im) = c("IM", "pCollapse")

    neo.collapse.im <- read.csv("example1a_collapse.txt", 
        header=TRUE, sep="")
    names(neo.collapse.im) = c("IM", "pCollapse")
  #+END_SRC
  
  #+RESULTS:

  Compare the two versions (assumes same IM values are used):
  #+BEGIN_SRC R :results value
    diff <- paleo.collapse.im$pCollapse -
        neo.collapse.im$pCollapse
    denom <- paleo.collapse.im$pCollapse
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e-05 (0.16%). |
  | Mean error is 3.850576e-07 (0.00%).     |

  Plot it:
  #+NAME: collapse-im
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM, 
         log="y", lwd=5,
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
        col=2, lwd=3)

    points(paleo2.collapse.im$pCollapse ~ 
  	 paleo2.collapse.im$IM, col=3)


    legend(x="right",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Probability of Collapse calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im
  #+RESULTS: collapse-im
  [[file:/tmp/babel-1789nf2/figure-1789jGM.pdf]]

  #+NAME: collapse-im-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM, 
         log="y", 
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         xlim=c(0, 0.5),
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
  	col=2)

    points(paleo2.collapse.im$pCollapse ~ 
  	 paleo2.collapse.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: COLLAPSE rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im-zoom
  #+RESULTS: collapse-im-zoom
  [[file:/tmp/babel-36639js/figure-3663BYR.pdf]]

  #+NAME: collapse-im-zoom2
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.collapse.im$pCollapse ~ paleo.collapse.im$IM,
         log="y", 
         xlab="IM", ylab="pCollapse", main="COLLAPSE Rate",
         xlim=c(1.5, 2.0),
         ylim=c(0.9, 1.0),
         type="p", col=1)

    lines(neo.collapse.im$pCollapse ~ neo.collapse.im$IM, 
  	col=2)

    points(paleo2.collapse.im$pCollapse ~
  	 paleo2.collapse.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: COLLAPSE rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:collapse-im-zoom2
  #+RESULTS: collapse-im-zoom2
  [[file:/tmp/babel-1789nf2/figure-1789SSd.pdf]]

  
  The overall rate of collapse:
  #+BEGIN_SRC R  :results value 
    paleo.rate <- scan(paste(results.dir, "collapse-rate", 
                             sep=""), skip=3)
    paleo2.rate <- scan(paste(results2.dir, "collapse-rate", 
                              sep=""), skip=3)
    neo.rate <- as.numeric(scan("example1a_collrate.txt", 
                                what="string")[8])
    paste(
        sprintf("Paleo: %e; Neo: %e; error: %3.2f%%", 
                paleo.rate,
                neo.rate, 
                (100*abs(neo.rate - paleo.rate)/paleo.rate)),
        sprintf("Paleo: %e; Paleo2: %e; error: %3.2f%%", 
                paleo.rate,
                paleo2.rate, 
                (100*abs(paleo2.rate-paleo.rate)/paleo.rate)),
        sep="\n")
  #+END_SRC
  
  #+RESULTS:
  | Paleo: 2.125500e-04; Neo: 2.158956e-04; error: 1.57%    |
  | Paleo: 2.125500e-04; Paleo2: 2.125500e-04; error: 0.00% |

* LOSS-IM
  Read the LOSS-IM data:
  #+BEGIN_SRC R   :results output
    paleo.loss.im <- read.csv(
        paste(results.dir, "pg-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.loss.im) = c("IM", "mean_x", "sd_ln_x")

    paleo2.loss.im <- read.csv(
        paste(results.dir, "pg-im", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.loss.im) = c("IM", "mean_x", "sd_ln_x")

    neo.loss.im <- read.csv("example1a_loss_im.txt", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:

  #+BEGIN_SRC R 
    diff <- paleo.loss.im$mean_x - neo.loss.im$mean_x
    denom <- paleo.loss.im$mean_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 9.460030e-01 (1751.95%). |
  | Mean error is -9.854146e-03 (-8.55%).      |

  Plot it (Figure [[fig:loss.im-mean]]):
  #+NAME: loss.im-mean
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.loss.im$mean_x ~ paleo.loss.im$IM, log="y", 
         xlab="IM", ylab="Mean Loss",
	 main="Loss-IM Relationship",
         type="p", col=1, lwd=5)

    lines(neo.loss.im$mean_x ~ neo.loss.im$IM, col=2, lwd=3)

    points(paleo.loss.im$mean_x ~ paleo.loss.im$IM, col=3)
    
    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-IM calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.im-mean
  #+RESULTS: loss.im-mean
  [[file:/tmp/babel-36639js/figure-3663Fct.pdf]]

  #+NAME: loss.im-mean-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.loss.im$mean_x ~ paleo.loss.im$IM, log="y", 
         xlab="IM", ylab="Mean Loss",
	 main="Loss-IM Relationship",
	 xlim=c(0.001, 0.10), ylim=c(1E-12, 1E0),
         type="p", col=1)

    lines(neo.loss.im$mean_x ~ neo.loss.im$IM, col=2)

    points(paleo.loss.im$mean_x ~ paleo.loss.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-IM calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.im-mean-zoom
  #+RESULTS: loss.im-mean-zoom
  [[file:/tmp/babel-36639js/figure-3663qUC.pdf]]

  #+BEGIN_SRC R 
    diff <- paleo.loss.im$sd_ln_x - neo.loss.im$sd_ln_x
    denom <- paleo.loss.im$sd_ln_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 2.000000e-03 (0.50%). |
  | Mean error is 1.249447e-04 (0.03%).     |


  #+NAME: loss.im-sd
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.loss.im$sd_ln_x ~ paleo.loss.im$IM, log="", 
         xlab="IM", ylab="sd(ln(Loss))", 
         main="Loss-IM Relationship",
         type="p", col=1)

    lines(neo.loss.im$sd_ln_x ~ neo.loss.im$IM, col=2)

    points(paleo.loss.im$sd_ln_x ~ paleo.loss.im$IM, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: LOSS.IM rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.im-sd
  #+RESULTS: loss.im-sd
  [[file:/tmp/babel-1772V7h/figure-1772H3N.pdf]]


* LOSS-EDP
  Read the LOSS-EDP data:
  #+BEGIN_SRC R   :results output
    paleo.loss.edp <- read.csv(
        paste(results.dir, "pg-edp", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.loss.edp) = c("EDP", "mean_x", "sd_ln_x")

    paleo2.loss.edp <- read.csv(
        paste(results.dir, "pg-edp", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.loss.edp) = c("EDP", "mean_x", "sd_ln_x")

    neo.loss.edp <- read.csv("example1a_loss_edp.txt", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:

  #+BEGIN_SRC R 
    diff <- paleo.loss.edp$mean_x - neo.loss.edp$mean_x
    denom <- paleo.loss.edp$mean_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e-05 (0.03%). |
  | Mean error is 1.506201e-06 (0.00%).     |

  #+BEGIN_SRC R 
    diff <- paleo.loss.edp$sd_ln_x - neo.loss.edp$sd_ln_x
    denom <- paleo.loss.edp$sd_ln_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e-04 (0.05%). |
  | Mean error is 4.953020e-06 (0.00%).     |

  Plot it:
  #+NAME: loss.edp-mean
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R
    palette(c("red", "blue", "green"))
    plot(paleo.loss.edp$mean_x ~ paleo.loss.edp$EDP, log="xy", 
         xlab="EDP", ylab="Mean(Loss)",
         main="Loss-EDP Relationship",
         type="p", col=1, lwd=5)

    lines(neo.loss.edp$mean_x ~ neo.loss.edp$EDP, 
        col=2, lwd=3)

    points(paleo2.loss.edp$mean_x ~ paleo2.loss.edp$EDP,
  	 col=3)

    legend(x="right",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+NAME: loss.edp-mean-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.loss.edp$mean_x ~ paleo.loss.edp$EDP, log="xy", 
         xlab="EDP", ylab="Mean(Loss)",
	 main="Loss-EDP Relationship",
         xlim=c(0.05, 0.10),
         ylim=c(5E-1, 1E0),
         type="p", col=1, lwd=5)

    lines(neo.loss.edp$mean_x ~ neo.loss.edp$EDP, 
  	col=2, lwd=3)

    points(paleo2.loss.edp$mean_x ~ paleo2.loss.edp$EDP, col=3)

    legend(x="right",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+RESULTS: loss.edp-mean-zoom
  [[file:/tmp/babel-1752Epe/figure-1752ssh.pdf]]

  #+CAPTION: Loss-EDP rate calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.edp-mean
  #+RESULTS: loss.edp-mean
  [[file:/tmp/babel-1752Epe/figure-175259b.pdf]]


  #+NAME: loss.edp-sd
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue", "green"))
    plot(paleo.loss.edp$sd_ln_x ~ paleo.loss.edp$EDP, log="", 
         xlab="EDP", ylab="sd(ln(Loss))",
	 main="Loss-EDP Relationship",
         type="p", col=1, lwd=5)
    lines(neo.loss.edp$sd_ln_x ~ neo.loss.edp$EDP, 
  	col=2, lwd=3)

    points(paleo.loss.edp$sd_ln_x ~ paleo.loss.edp$EDP, col=3)

    legend(x="right",
         legend=c("Paleo", "Neo"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-EDP calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.edp-sd
  #+RESULTS: loss.edp-sd
  [[file:/tmp/babel-1752Epe/figure-1752ngK.pdf]]


  #+NAME: loss.edp-sd-zoom
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R 
    palette(c("red", "blue", "green"))
    plot(paleo.loss.edp$sd_ln_x ~ paleo.loss.edp$EDP, log="", 
         xlab="EDP", ylab="sd(ln(Loss))",
	 main="Loss-EDP Relationship",
         xlim=c(0.08, 0.12),
         ylim=c(0.4, 0.85),
         type="p", col=1, lwd=5)

    lines(neo.loss.edp$sd_ln_x ~ neo.loss.edp$EDP, 
  	col=2, lwd=3)

    points(paleo.loss.edp$sd_ln_x ~ paleo.loss.edp$EDP, col=3)

    legend(x="topright",
         legend=c("Paleo", "Neo", "Paleo2"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-EDP calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:loss.edp-sd-zoom
  #+RESULTS: loss.edp-sd-zoom
  [[file:/tmp/babel-1752Epe/figure-1752kGv.pdf]]

* Annual Loss
  
  #+BEGIN_SRC R   :results output
    paleo.loss.edp <- read.csv(
        paste(results.dir, "pg-edp", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.loss.edp) = c("EDP", "mean_x",
             "sd_ln_x")

    paleo2.loss.edp <- read.csv(
        paste(results.dir, "pg-edp", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo2.loss.edp) = c("EDP", "mean_x",
             "sd_ln_x")

    neo.loss.edp <- read.csv("example1a_loss_edp.txt", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:

  #+BEGIN_SRC R 
    diff <- paleo.loss.edp$mean_x - neo.loss.edp$mean_x
    denom <- paleo.loss.edp$mean_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e-05 (0.03%). |
  | Mean error is 1.506201e-06 (0.00%).     |

* Total Loss
  Read the Total Loss data:
  #+BEGIN_SRC R   :results output
    paleo.structloss.c <- read.csv(
        paste(results.dir, "tlossc", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.structloss.c) = c("IM", "mean_x", "sd_ln_x")

    paleo.structloss.nc <- read.csv(
        paste(results.dir, "tlossnc", sep=""),
        skip=3, header=FALSE, sep="")
    names(paleo.structloss.nc) = c("IM", "mean_x", "sd_ln_x")

    neo.structloss.c <- read.csv("example1a_loss_c_total", 
        header=TRUE, sep="")

    neo.structloss.nc <- read.csv("example1a_loss_nc_total", 
        header=TRUE, sep="")
  #+END_SRC
  
  #+RESULTS:
* Non-Collapse
  #+BEGIN_SRC R 
    diff <- paleo.structloss.nc$mean_x -
        neo.structloss.nc$mean_x
    denom <- paleo.structloss.nc$mean_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),

        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 1.040000e-02 (1.05%). |
  | Mean error is -5.910834e-04 (-0.06%).   |

  #+BEGIN_SRC R 
    diff <- paleo.structloss.nc$sd_ln_x - 
        neo.structloss.nc$sd_ln_x
    denom <- paleo.structloss.nc$sd_ln_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 1.340000e+00 (100.00%). |
  | Mean error is 4.142432e-01 (100.00%).     |

  Plot it:
  #+NAME: structloss.nc-mean
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R
    palette(c("red", "blue"))
    plot(paleo.structloss.nc$mean_x ~
         paleo.structloss.nc$IM, log="xy", 
         xlab="IM", ylab="Mean(Loss)", 
         main="Total Loss, No Collapse",
         type="p", col=1, lwd=5)

    lines(neo.structloss.nc$mean_x ~ neo.structloss.nc$IM, 
        col=2, lwd=3)

    legend(x="topright",
         legend=c("Paleo", "Neo"),
         fill=palette())
  #+END_SRC

  #+RESULTS: structloss.nc-mean
  [[file:/tmp/babel-1752Epe/figure-1752-hv.pdf]]


  #+NAME: structloss.nc-sd
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue"))
    plot(paleo.structloss.nc$sd_ln_x ~ paleo.structloss.nc$IM, 
         log="", xlab="EDP", ylab="sd(ln(Loss))", 
         main="Total Loss, No Collapse",
         ylim=c(0, max(paleo.structloss.nc$sd_ln_x)),
         type="p", col=1, lwd=5)
    lines(neo.structloss.nc$sd_ln_x ~ neo.structloss.nc$IM, 
        col=2, lwd=3)

    legend(x="topright",
         legend=c("Paleo", "Neo"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-EDP calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:structloss.nc-sd
  #+RESULTS: structloss.nc-sd
  [[file:/tmp/babel-1752Epe/figure-1752KAL.pdf]]



* Collapse
  #+BEGIN_SRC R 
    diff <- paleo.structloss.c$mean_x - 
        neo.structloss.c$mean_x
    denom <- paleo.structloss.c$mean_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 5.000000e+02 (0.11%). |
  | Mean error is -2.800722e+01 (-0.00%).   |

  #+BEGIN_SRC R 
    diff <- paleo.structloss.c$sd_ln_x - 
        neo.structloss.c$sd_ln_x
    denom <- paleo.structloss.c$sd_ln_x
    denom[denom == 0] <- NA
    diff.pct <- diff / denom

    paste(
        sprintf("Max abs(error) is %e (%3.2f%%).",
                max(abs(diff)),
                100 * max(abs(diff.pct), na.rm=TRUE)),
        sprintf("Mean error is %e (%3.2f%%).",
                mean(diff),
                100 * mean(diff.pct, na.rm=TRUE)),
        sep="\n")
  #+END_SRC

  #+RESULTS:
  | Max abs(error) is 3.886000e+00 (100.00%). |
  | Mean error is 9.389256e-01 (100.00%).     |

  Plot it:
  #+NAME: structloss.c-mean
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R
    palette(c("red", "blue"))
    plot(paleo.structloss.c$mean_x ~ paleo.structloss.c$IM, 
         log="xy", xlab="IM", ylab="Mean(Loss)", 
         main="Total Loss, Collapse",
         type="p", col=1, lwd=5)

    lines(neo.structloss.c$mean_x ~ neo.structloss.c$IM, 
        col=2, lwd=3)

    legend(x="topright",
         legend=c("Paleo", "Neo"),
         fill=palette())
  #+END_SRC

  #+RESULTS: structloss.c-mean
  [[file:/tmp/babel-1752Epe/figure-1752qno.pdf]]


  #+NAME: structloss.c-sd
  #+HEADER: :results graphics
  #+HEADER: :file (org-babel-temp-file "./figure-" ".pdf")
  #+BEGIN_SRC R  
    palette(c("red", "blue"))
    plot(paleo.structloss.c$sd_ln_x ~ paleo.structloss.c$IM, log="", 
         xlab="EDP", ylab="sd(ln(Loss))", main="Total Loss, Collapse",
	 ylim=c(0, max(paleo.structloss.c$sd_ln_x)),
         type="p", col=1, lwd=5)
    lines(neo.structloss.c$sd_ln_x ~ neo.structloss.c$IM, 
  	col=2, lwd=3)

    legend(x="topright",
         legend=c("Paleo", "Neo"),
         fill=palette())
  #+END_SRC

  #+CAPTION: Loss-EDP calculations
  #+ATTR_LaTeX: :width \textwidth*4/4 :placement [h!bt]
  #+NAME: fig:structloss.c-sd
  #+RESULTS: structloss.c-sd
  [[file:/tmp/babel-1752Epe/figure-175267C.pdf]]


